NAME = mine
SOURCES = hello.cc \
		add_something.cc \
		clone_wire.cc \
		module_from_scratch.cc \
		tmr_try.cc \
		tmr_try_hier.cc \
		insert_voter.cc \
		apply_tmr.cc \
		cell_primitive_info.cc \
		view_info.cc \
		collect_connections.cc
		# tmr_and_check.cc

include ../Makefile_plugin.common