/* Generated by Yosys 0.17+41 (git sha1 c525b5f91, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* dynports =  1  *)
(* hdlname = "\\mod_counter" *)
(* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:17.1-35.10" *)
module \$paramod$af89ed8d08c8018cd41487cbf58ed920a4905fc9\mod_counter (clk, reset, increment, rolling_over, count);
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:84.12-84.14" *)
  wire _00_;
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:84.16-84.18" *)
  wire _01_;
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:86.46-86.71|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:78.16-78.18" *)
  wire _02_;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:27.7-27.28" *)
  wire _03_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18" *)
  wire [18:0] _04_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:112.23-112.24" *)
  wire [18:0] _05_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:112.26-112.27" *)
  wire [18:0] _06_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:170.23-170.24" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18 19" *)
  wire [19:0] _07_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:168.23-168.24" *)
  (* unused_bits = "19" *)
  wire [19:0] _08_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _09_;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:18.19-18.22" *)
  input clk;
  wire clk;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:22.36-22.41" *)
  output [18:0] count;
  wire [18:0] count;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:20.19-20.28" *)
  input increment;
  wire increment;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:19.19-19.24" *)
  input reset;
  wire reset;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:21.15-21.27" *)
  output rolling_over;
  wire rolling_over;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147483648)
  ) _10_ (
    .I0(_09_[4]),
    .I1(_09_[0]),
    .I2(_09_[1]),
    .I3(_09_[2]),
    .I4(_09_[3]),
    .O(rolling_over)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:85.46-85.71|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _11_ (
    .I0(1'h0),
    .I1(1'h0),
    .O(_00_),
    .S(count[16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:86.46-86.71|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:80.45-80.70|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0000000100000000)
  ) _12_ (
    .I0(count[0]),
    .I1(count[1]),
    .I2(count[2]),
    .I3(count[3]),
    .I4(count[4]),
    .I5(count[15]),
    .O(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:86.46-86.71|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _13_ (
    .I0(1'h0),
    .I1(_02_),
    .O(_01_),
    .S(count[16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:87.13-87.52" *)
  MUXF8 _14_ (
    .I0(_00_),
    .I1(_01_),
    .O(_09_[4]),
    .S(count[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h8000)
  ) _15_ (
    .I0(count[5]),
    .I1(count[8]),
    .I2(count[17]),
    .I3(count[18]),
    .O(_09_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _16_ (
    .I0(count[11]),
    .I1(count[12]),
    .O(_09_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _17_ (
    .I0(count[14]),
    .I1(increment),
    .O(_09_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0001)
  ) _18_ (
    .I0(count[6]),
    .I1(count[7]),
    .I2(count[9]),
    .I3(count[10]),
    .O(_09_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hffffffff80000000)
  ) _19_ (
    .I0(_09_[0]),
    .I1(_09_[1]),
    .I2(_09_[2]),
    .I3(_09_[3]),
    .I4(_09_[4]),
    .I5(reset),
    .O(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _20_ (
    .I(count[0]),
    .O(_05_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _21_ (
    .CI(1'h0),
    .CO(_04_[3:0]),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O(_06_[3:0]),
    .S({ count[3:1], _05_[0] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _22_ (
    .CI(_04_[3]),
    .CO(_04_[7:4]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_06_[7:4]),
    .S(count[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _23_ (
    .CI(_04_[7]),
    .CO(_04_[11:8]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_06_[11:8]),
    .S(count[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _24_ (
    .CI(_04_[11]),
    .CO(_04_[15:12]),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O(_06_[15:12]),
    .S(count[15:12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _25_ (
    .CI(_04_[15]),
    .CO({ _07_[19], _04_[18:16] }),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _08_[19], _06_[18:16] }),
    .S({ 1'h0, count[18:16] })
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _26_ (
    .C(clk),
    .CE(increment),
    .D(_06_[0]),
    .Q(count[0]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _27_ (
    .C(clk),
    .CE(increment),
    .D(_06_[1]),
    .Q(count[1]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _28_ (
    .C(clk),
    .CE(increment),
    .D(_06_[2]),
    .Q(count[2]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _29_ (
    .C(clk),
    .CE(increment),
    .D(_06_[3]),
    .Q(count[3]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _30_ (
    .C(clk),
    .CE(increment),
    .D(_06_[4]),
    .Q(count[4]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _31_ (
    .C(clk),
    .CE(increment),
    .D(_06_[5]),
    .Q(count[5]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _32_ (
    .C(clk),
    .CE(increment),
    .D(_06_[6]),
    .Q(count[6]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _33_ (
    .C(clk),
    .CE(increment),
    .D(_06_[7]),
    .Q(count[7]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _34_ (
    .C(clk),
    .CE(increment),
    .D(_06_[8]),
    .Q(count[8]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _35_ (
    .C(clk),
    .CE(increment),
    .D(_06_[9]),
    .Q(count[9]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _36_ (
    .C(clk),
    .CE(increment),
    .D(_06_[10]),
    .Q(count[10]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _37_ (
    .C(clk),
    .CE(increment),
    .D(_06_[11]),
    .Q(count[11]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _38_ (
    .C(clk),
    .CE(increment),
    .D(_06_[12]),
    .Q(count[12]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _39_ (
    .C(clk),
    .CE(increment),
    .D(_06_[13]),
    .Q(count[13]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _40_ (
    .C(clk),
    .CE(increment),
    .D(_06_[14]),
    .Q(count[14]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _41_ (
    .C(clk),
    .CE(increment),
    .D(_06_[15]),
    .Q(count[15]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _42_ (
    .C(clk),
    .CE(increment),
    .D(_06_[16]),
    .Q(count[16]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _43_ (
    .C(clk),
    .CE(increment),
    .D(_06_[17]),
    .Q(count[17]),
    .R(_03_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _44_ (
    .C(clk),
    .CE(increment),
    .D(_06_[18]),
    .Q(count[18]),
    .R(_03_)
  );
  assign _09_[5] = reset;
  assign _05_[18:1] = count[18:1];
  assign _07_[18:0] = _04_;
  assign _08_[18:0] = _06_;
endmodule

(* hdlname = "\\debounce" *)
(* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce.sv:16.1-93.10" *)
module debounce(clk, reset, noisy, debounced);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce.sv:17.19-17.22" *)
  input clk;
  wire clk;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce.sv:22.11-22.19" *)
  wire clrTimer;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce.sv:25.17-25.22" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18" *)
  wire [18:0] count;
  (* onehot = 32'd1 *)
  wire [3:0] cs;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce.sv:18.18-18.27" *)
  output debounced;
  wire debounced;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce.sv:17.31-17.36" *)
  input noisy;
  wire noisy;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce.sv:17.24-17.29" *)
  input reset;
  wire reset;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce.sv:22.21-22.30" *)
  wire timerDone;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0000fff800000000)
  ) _04_ (
    .I0(cs[2]),
    .I1(timerDone),
    .I2(cs[3]),
    .I3(cs[1]),
    .I4(reset),
    .I5(noisy),
    .O(_01_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd15990784)
  ) _05_ (
    .I0(timerDone),
    .I1(cs[2]),
    .I2(cs[0]),
    .I3(reset),
    .I4(noisy),
    .O(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd244)
  ) _06_ (
    .I0(timerDone),
    .I1(cs[3]),
    .I2(cs[1]),
    .I3(reset),
    .I4(noisy),
    .O(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hffffffff0f0f0f08)
  ) _07_ (
    .I0(timerDone),
    .I1(cs[3]),
    .I2(noisy),
    .I3(cs[0]),
    .I4(cs[2]),
    .I5(reset),
    .O(_00_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h01)
  ) _08_ (
    .I0(cs[2]),
    .I1(cs[3]),
    .I2(reset),
    .O(clrTimer)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h0e)
  ) _09_ (
    .I0(cs[3]),
    .I1(cs[1]),
    .I2(reset),
    .O(debounced)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _10_ (
    .C(clk),
    .CE(1'h1),
    .D(_00_),
    .Q(cs[0]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _11_ (
    .C(clk),
    .CE(1'h1),
    .D(_01_),
    .Q(cs[1]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _12_ (
    .C(clk),
    .CE(1'h1),
    .D(_02_),
    .Q(cs[2]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _13_ (
    .C(clk),
    .CE(1'h1),
    .D(_03_),
    .Q(cs[3]),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce.sv:86.31-86.121" *)
  \$paramod$af89ed8d08c8018cd41487cbf58ed920a4905fc9\mod_counter  timer (
    .clk(clk),
    .count(count),
    .increment(1'h1),
    .reset(clrTimer),
    .rolling_over(timerDone)
  );
endmodule

(* hdlname = "\\debounce_top" *)
(* top =  1  *)
(* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:16.1-75.10" *)
module debounce_top(clk, reset, increment, debouncedOutput, noisyOutput);
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:29.5-30.37" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:34.39-34.45" *)
  wire _029_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:50.23-50.39|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6" *)
  wire [6:0] _030_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:50.23-50.39|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:112.26-112.27" *)
  wire [6:0] _031_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:50.23-50.39|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:170.23-170.24" *)
  (* unused_bits = "0 1 2 4 5 6 7" *)
  wire [7:0] _032_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:50.23-50.39|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:168.23-168.24" *)
  (* unused_bits = "7" *)
  wire [7:0] _033_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:68.19-68.31|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6" *)
  wire [6:0] _034_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:68.19-68.31|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:112.26-112.27" *)
  wire [6:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:68.19-68.31|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:170.23-170.24" *)
  (* unused_bits = "0 1 2 4 5 6 7" *)
  wire [7:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:68.19-68.31|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:168.23-168.24" *)
  (* unused_bits = "7" *)
  wire [7:0] _037_;
  wire _038_;
  wire _039_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire _040_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire _041_;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:25.11-25.13" *)
  wire F1;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:25.15-25.17" *)
  wire F2;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:25.19-25.21" *)
  wire F3;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:25.23-25.25" *)
  wire F4;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:23.16-23.26" *)
  wire [1:0] buttonPush;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:17.22-17.25" *)
  input clk;
  wire clk;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:26.16-26.30" *)
  wire [6:0] debouncedCount;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:18.20-18.35" *)
  output [6:0] debouncedOutput;
  wire [6:0] debouncedOutput;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:24.11-24.24" *)
  wire debouncedPush;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:17.34-17.43" *)
  input increment;
  wire increment;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:26.32-26.42" *)
  wire [6:0] noisyCount;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:18.37-18.48" *)
  output [6:0] noisyOutput;
  wire [6:0] noisyOutput;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:25.27-25.33" *)
  wire pulse1;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:25.35-25.41" *)
  wire pulse2;
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:17.27-17.32" *)
  input reset;
  wire reset;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _042_ (
    .I0(F2),
    .I1(F1),
    .O(pulse1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _043_ (
    .I0(F4),
    .I1(F3),
    .O(pulse2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _044_ (
    .I(_040_),
    .O(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _045_ (
    .I(debouncedCount[0]),
    .O(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _046_ (
    .I(_041_),
    .O(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _047_ (
    .I(debouncedCount[4]),
    .O(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _048_ (
    .I(noisyCount[2]),
    .O(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _049_ (
    .I(noisyCount[3]),
    .O(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _050_ (
    .I(noisyCount[4]),
    .O(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _051_ (
    .I(noisyCount[5]),
    .O(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _052_ (
    .I(noisyCount[0]),
    .O(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _053_ (
    .I(noisyCount[1]),
    .O(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _054_ (
    .I(noisyCount[6]),
    .O(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _055_ (
    .I(debouncedCount[1]),
    .O(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _056_ (
    .I(debouncedCount[2]),
    .O(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _057_ (
    .I(debouncedCount[3]),
    .O(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _058_ (
    .I(debouncedCount[5]),
    .O(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _059_ (
    .I(debouncedCount[6]),
    .O(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _060_ (
    .I(_040_),
    .O(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _061_ (
    .I(_040_),
    .O(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _062_ (
    .I(_040_),
    .O(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _063_ (
    .I(_040_),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _064_ (
    .I(_040_),
    .O(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _065_ (
    .I(_040_),
    .O(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _066_ (
    .I(_040_),
    .O(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _067_ (
    .I(_040_),
    .O(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _068_ (
    .I(_040_),
    .O(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _069_ (
    .I(_040_),
    .O(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _070_ (
    .I(_040_),
    .O(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _071_ (
    .I(_040_),
    .O(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _072_ (
    .I(_040_),
    .O(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _073_ (
    .I(_040_),
    .O(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:50.23-50.39|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _074_ (
    .CI(1'h0),
    .CO(_030_[3:0]),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O(_031_[3:0]),
    .S({ debouncedCount[3:1], _015_ })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:50.23-50.39|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _075_ (
    .CI(_030_[3]),
    .CO({ _032_[7], _030_[6:4] }),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _033_[7], _031_[6:4] }),
    .S({ 1'h0, debouncedCount[6:4] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:68.19-68.31|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _076_ (
    .CI(1'h0),
    .CO(_034_[3:0]),
    .CYINIT(1'h0),
    .DI(4'h1),
    .O(_035_[3:0]),
    .S({ noisyCount[3:1], _022_ })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:68.19-68.31|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _077_ (
    .CI(_034_[3]),
    .CO({ _036_[7], _034_[6:4] }),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _037_[7], _035_[6:4] }),
    .S({ 1'h0, noisyCount[6:4] })
  );
  BUFG _078_ (
    .I(_038_),
    .O(_039_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:62.5-70.16|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _079_ (
    .C(_039_),
    .CE(pulse2),
    .D(_035_[0]),
    .Q(noisyCount[0]),
    .R(_001_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:62.5-70.16|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _080_ (
    .C(_039_),
    .CE(pulse2),
    .D(_035_[1]),
    .Q(noisyCount[1]),
    .R(_002_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:62.5-70.16|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _081_ (
    .C(_039_),
    .CE(pulse2),
    .D(_035_[2]),
    .Q(noisyCount[2]),
    .R(_003_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:62.5-70.16|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _082_ (
    .C(_039_),
    .CE(pulse2),
    .D(_035_[3]),
    .Q(noisyCount[3]),
    .R(_004_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:62.5-70.16|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _083_ (
    .C(_039_),
    .CE(pulse2),
    .D(_035_[4]),
    .Q(noisyCount[4]),
    .R(_005_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:62.5-70.16|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _084_ (
    .C(_039_),
    .CE(pulse2),
    .D(_035_[5]),
    .Q(noisyCount[5]),
    .R(_006_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:62.5-70.16|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _085_ (
    .C(_039_),
    .CE(pulse2),
    .D(_035_[6]),
    .Q(noisyCount[6]),
    .R(_007_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:57.5-58.18|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _086_ (
    .C(_039_),
    .CE(1'h1),
    .D(F3),
    .Q(F4),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:55.5-56.29|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _087_ (
    .C(_039_),
    .CE(1'h1),
    .D(buttonPush[1]),
    .Q(F3),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:44.5-52.7|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _088_ (
    .C(_039_),
    .CE(pulse1),
    .D(_031_[0]),
    .Q(debouncedCount[0]),
    .R(_008_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:44.5-52.7|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _089_ (
    .C(_039_),
    .CE(pulse1),
    .D(_031_[1]),
    .Q(debouncedCount[1]),
    .R(_009_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:44.5-52.7|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _090_ (
    .C(_039_),
    .CE(pulse1),
    .D(_031_[2]),
    .Q(debouncedCount[2]),
    .R(_010_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:44.5-52.7|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _091_ (
    .C(_039_),
    .CE(pulse1),
    .D(_031_[3]),
    .Q(debouncedCount[3]),
    .R(_011_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:44.5-52.7|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _092_ (
    .C(_039_),
    .CE(pulse1),
    .D(_031_[4]),
    .Q(debouncedCount[4]),
    .R(_012_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:44.5-52.7|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _093_ (
    .C(_039_),
    .CE(pulse1),
    .D(_031_[5]),
    .Q(debouncedCount[5]),
    .R(_013_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:44.5-52.7|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _094_ (
    .C(_039_),
    .CE(pulse1),
    .D(_031_[6]),
    .Q(debouncedCount[6]),
    .R(_014_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:39.5-40.18|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _095_ (
    .C(_039_),
    .CE(1'h1),
    .D(F1),
    .Q(F2),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:37.5-38.29|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _096_ (
    .C(_039_),
    .CE(1'h1),
    .D(debouncedPush),
    .Q(F1),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:31.5-32.40|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _097_ (
    .C(_039_),
    .CE(1'h1),
    .D(buttonPush[0]),
    .Q(buttonPush[1]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:29.5-30.37|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _098_ (
    .C(_039_),
    .CE(1'h1),
    .D(_000_),
    .Q(buttonPush[0]),
    .R(1'h0)
  );
  (* keep = 32'd1 *)
  IBUF _099_ (
    .I(clk),
    .O(_038_)
  );
  (* keep = 32'd1 *)
  OBUF _100_ (
    .I(_015_),
    .O(debouncedOutput[0])
  );
  (* keep = 32'd1 *)
  OBUF _101_ (
    .I(_016_),
    .O(debouncedOutput[1])
  );
  (* keep = 32'd1 *)
  OBUF _102_ (
    .I(_017_),
    .O(debouncedOutput[2])
  );
  (* keep = 32'd1 *)
  OBUF _103_ (
    .I(_018_),
    .O(debouncedOutput[3])
  );
  (* keep = 32'd1 *)
  OBUF _104_ (
    .I(_019_),
    .O(debouncedOutput[4])
  );
  (* keep = 32'd1 *)
  OBUF _105_ (
    .I(_020_),
    .O(debouncedOutput[5])
  );
  (* keep = 32'd1 *)
  OBUF _106_ (
    .I(_021_),
    .O(debouncedOutput[6])
  );
  (* keep = 32'd1 *)
  IBUF _107_ (
    .I(increment),
    .O(_041_)
  );
  (* keep = 32'd1 *)
  OBUF _108_ (
    .I(_022_),
    .O(noisyOutput[0])
  );
  (* keep = 32'd1 *)
  OBUF _109_ (
    .I(_023_),
    .O(noisyOutput[1])
  );
  (* keep = 32'd1 *)
  OBUF _110_ (
    .I(_024_),
    .O(noisyOutput[2])
  );
  (* keep = 32'd1 *)
  OBUF _111_ (
    .I(_025_),
    .O(noisyOutput[3])
  );
  (* keep = 32'd1 *)
  OBUF _112_ (
    .I(_026_),
    .O(noisyOutput[4])
  );
  (* keep = 32'd1 *)
  OBUF _113_ (
    .I(_027_),
    .O(noisyOutput[5])
  );
  (* keep = 32'd1 *)
  OBUF _114_ (
    .I(_028_),
    .O(noisyOutput[6])
  );
  (* keep = 32'd1 *)
  IBUF _115_ (
    .I(reset),
    .O(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys_plugins/yosys-f4pga-plugins/yosys_help_test/counter/debounce_top.sv:34.11-34.95" *)
  debounce debouncer (
    .clk(_039_),
    .debounced(debouncedPush),
    .noisy(buttonPush[1]),
    .reset(_029_)
  );
  assign _032_[6:0] = _030_;
  assign _033_[6:0] = _031_;
  assign _036_[6:0] = _034_;
  assign _037_[6:0] = _035_;
endmodule
