/* Generated by Yosys 0.17+41 (git sha1 c525b5f91, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
module new_module(_01_, _02_, _03_, _04_);
  wire _00_;
  input _01_;
  wire _01_;
  input _02_;
  wire _02_;
  input _03_;
  wire _03_;
  output _04_;
  wire _04_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _05_;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'he8)
  ) _06_ (
    .I0(_05_[0]),
    .I1(_05_[1]),
    .I2(_05_[2]),
    .O(_00_)
  );
  (* keep = 32'd1 *)
  IBUF _07_ (
    .I(_01_),
    .O(_05_[0])
  );
  (* keep = 32'd1 *)
  IBUF _08_ (
    .I(_02_),
    .O(_05_[1])
  );
  (* keep = 32'd1 *)
  IBUF _09_ (
    .I(_03_),
    .O(_05_[2])
  );
  (* keep = 32'd1 *)
  OBUF _10_ (
    .I(_00_),
    .O(_04_)
  );
endmodule
