/* Generated by Yosys 0.17+41 (git sha1 c525b5f91, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* dynports =  1  *)
(* hdlname = "\\mod_counter" *)
(* src = "counter/mod_counter.sv:17.1-35.10" *)
module \$paramod$af89ed8d08c8018cd41487cbf58ed920a4905fc9\mod_counter (clk, reset, increment, rolling_over, count);
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [6:0] _00_;
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:78.12-78.14" *)
  wire _01_;
  (* src = "counter/mod_counter.sv:27.7-27.28" *)
  wire _02_;
  (* force_downto = 32'd1 *)
  (* src = "counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18" *)
  wire [18:0] _03_;
  (* force_downto = 32'd1 *)
  (* src = "counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:112.23-112.24" *)
  wire [18:0] _04_;
  (* force_downto = 32'd1 *)
  (* src = "counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:112.26-112.27" *)
  wire [18:0] _05_;
  (* force_downto = 32'd1 *)
  (* src = "counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:170.23-170.24" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18 19" *)
  wire [19:0] _06_;
  (* force_downto = 32'd1 *)
  (* src = "counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:168.23-168.24" *)
  (* unused_bits = "19" *)
  wire [19:0] _07_;
  (* src = "counter/mod_counter.sv:18.19-18.22" *)
  input clk;
  wire clk;
  (* src = "counter/mod_counter.sv:22.36-22.41" *)
  output [18:0] count;
  wire [18:0] count;
  (* src = "counter/mod_counter.sv:20.19-20.28" *)
  input increment;
  wire increment;
  (* src = "counter/mod_counter.sv:19.19-19.24" *)
  input reset;
  wire reset;
  (* src = "counter/mod_counter.sv:21.15-21.27" *)
  output rolling_over;
  wire rolling_over;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _08_ (
    .C(clk),
    .CE(increment),
    .D(_05_[18]),
    .Q(count[18]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _09_ (
    .C(clk),
    .CE(increment),
    .D(_05_[0]),
    .Q(count[0]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _10_ (
    .C(clk),
    .CE(increment),
    .D(_05_[1]),
    .Q(count[1]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _11_ (
    .C(clk),
    .CE(increment),
    .D(_05_[2]),
    .Q(count[2]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _12_ (
    .C(clk),
    .CE(increment),
    .D(_05_[3]),
    .Q(count[3]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _13_ (
    .C(clk),
    .CE(increment),
    .D(_05_[4]),
    .Q(count[4]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _14_ (
    .C(clk),
    .CE(increment),
    .D(_05_[5]),
    .Q(count[5]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _15_ (
    .C(clk),
    .CE(increment),
    .D(_05_[6]),
    .Q(count[6]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _16_ (
    .C(clk),
    .CE(increment),
    .D(_05_[7]),
    .Q(count[7]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _17_ (
    .C(clk),
    .CE(increment),
    .D(_05_[8]),
    .Q(count[8]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _18_ (
    .C(clk),
    .CE(increment),
    .D(_05_[9]),
    .Q(count[9]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _19_ (
    .C(clk),
    .CE(increment),
    .D(_05_[10]),
    .Q(count[10]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _20_ (
    .C(clk),
    .CE(increment),
    .D(_05_[11]),
    .Q(count[11]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _21_ (
    .C(clk),
    .CE(increment),
    .D(_05_[12]),
    .Q(count[12]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _22_ (
    .C(clk),
    .CE(increment),
    .D(_05_[13]),
    .Q(count[13]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _23_ (
    .C(clk),
    .CE(increment),
    .D(_05_[14]),
    .Q(count[14]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _24_ (
    .C(clk),
    .CE(increment),
    .D(_05_[15]),
    .Q(count[15]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _25_ (
    .C(clk),
    .CE(increment),
    .D(_05_[16]),
    .Q(count[16]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _26_ (
    .C(clk),
    .CE(increment),
    .D(_05_[17]),
    .Q(count[17]),
    .R(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'b1000000000000000000000000000000000000000000000000000000000000000)
  ) _27_ (
    .I0(_00_[5]),
    .I1(_00_[0]),
    .I2(_00_[1]),
    .I3(_00_[2]),
    .I4(_00_[3]),
    .I5(_00_[4]),
    .O(rolling_over)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'b0000000100000000)
  ) _28_ (
    .I0(count[2]),
    .I1(count[3]),
    .I2(count[4]),
    .I3(count[5]),
    .O(_00_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'b1000)
  ) _29_ (
    .I0(increment),
    .I1(count[18]),
    .O(_00_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'b0001)
  ) _30_ (
    .I0(count[0]),
    .I1(count[1]),
    .O(_00_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'b0100000000000000)
  ) _31_ (
    .I0(count[14]),
    .I1(count[15]),
    .I2(count[16]),
    .I3(count[17]),
    .O(_00_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'b0000000100000000)
  ) _32_ (
    .I0(count[10]),
    .I1(count[11]),
    .I2(count[12]),
    .I3(count[13]),
    .O(_00_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'b0000000100000000)
  ) _33_ (
    .I0(count[6]),
    .I1(count[7]),
    .I2(count[9]),
    .I3(count[8]),
    .O(_00_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:79.45-79.70|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'b1000000000000000000000000000000000000000000000000000000000000000)
  ) _34_ (
    .I0(_00_[0]),
    .I1(_00_[1]),
    .I2(_00_[2]),
    .I3(_00_[3]),
    .I4(_00_[4]),
    .I5(_00_[5]),
    .O(_01_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _35_ (
    .I0(_01_),
    .I1(1'b1),
    .O(_02_),
    .S(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _36_ (
    .I(count[0]),
    .O(_04_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _37_ (
    .CI(1'b0),
    .CO(_03_[3:0]),
    .CYINIT(1'b0),
    .DI(4'b0001),
    .O(_05_[3:0]),
    .S({ count[3:1], _04_[0] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _38_ (
    .CI(_03_[3]),
    .CO(_03_[7:4]),
    .CYINIT(1'b0),
    .DI(4'b0000),
    .O(_05_[7:4]),
    .S(count[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _39_ (
    .CI(_03_[7]),
    .CO(_03_[11:8]),
    .CYINIT(1'b0),
    .DI(4'b0000),
    .O(_05_[11:8]),
    .S(count[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _40_ (
    .CI(_03_[11]),
    .CO(_03_[15:12]),
    .CYINIT(1'b0),
    .DI(4'b0000),
    .O(_05_[15:12]),
    .S(count[15:12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _41_ (
    .CI(_03_[15]),
    .CO({ _06_[19], _03_[18:16] }),
    .CYINIT(1'b0),
    .DI(4'b0000),
    .O({ _07_[19], _05_[18:16] }),
    .S({ 1'b0, count[18:16] })
  );
  assign _00_[6] = reset;
  assign _04_[18:1] = count[18:1];
  assign _06_[18:0] = _03_;
  assign _07_[18:0] = _05_;
endmodule

(* hdlname = "\\debounce" *)
(* src = "counter/debounce.sv:16.1-93.10" *)
module debounce(clk, reset, noisy, debounced);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _04_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _05_;
  (* src = "counter/debounce.sv:17.19-17.22" *)
  input clk;
  wire clk;
  (* src = "counter/debounce.sv:22.11-22.19" *)
  wire clrTimer;
  (* src = "counter/debounce.sv:25.17-25.22" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18" *)
  wire [18:0] count;
  (* src = "counter/debounce.sv:18.18-18.27" *)
  output debounced;
  wire debounced;
  (* src = "counter/debounce.sv:17.31-17.36" *)
  input noisy;
  wire noisy;
  (* src = "counter/debounce.sv:17.24-17.29" *)
  input reset;
  wire reset;
  (* src = "counter/debounce.sv:22.21-22.30" *)
  wire timerDone;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _06_ (
    .C(clk),
    .CE(1'b1),
    .D(_00_),
    .Q(_04_[3]),
    .R(1'b0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _07_ (
    .C(clk),
    .CE(1'b1),
    .D(_01_),
    .Q(_05_[3]),
    .R(1'b0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _08_ (
    .C(clk),
    .CE(1'b1),
    .D(_02_),
    .Q(_04_[2]),
    .R(1'b0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _09_ (
    .C(clk),
    .CE(1'b1),
    .D(_03_),
    .Q(_04_[1]),
    .R(1'b0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'b00000001)
  ) _10_ (
    .I0(reset),
    .I1(_04_[3]),
    .I2(_04_[1]),
    .O(clrTimer)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'b00001110)
  ) _11_ (
    .I0(_04_[2]),
    .I1(_04_[3]),
    .I2(reset),
    .O(debounced)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd244)
  ) _12_ (
    .I0(timerDone),
    .I1(_04_[3]),
    .I2(_04_[2]),
    .I3(noisy),
    .I4(reset),
    .O(_00_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'b1111111111111111111111111111111100001111000011110000111100001000)
  ) _13_ (
    .I0(_04_[3]),
    .I1(timerDone),
    .I2(noisy),
    .I3(_05_[3]),
    .I4(_04_[1]),
    .I5(reset),
    .O(_01_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'b0000000000000000111111111111100000000000000000000000000000000000)
  ) _14_ (
    .I0(timerDone),
    .I1(_04_[1]),
    .I2(_04_[2]),
    .I3(_04_[3]),
    .I4(reset),
    .I5(noisy),
    .O(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd15990784)
  ) _15_ (
    .I0(timerDone),
    .I1(_04_[1]),
    .I2(_05_[3]),
    .I3(reset),
    .I4(noisy),
    .O(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter/debounce.sv:86.31-86.121" *)
  \$paramod$af89ed8d08c8018cd41487cbf58ed920a4905fc9\mod_counter  timer (
    .clk(clk),
    .count(count),
    .increment(1'b1),
    .reset(clrTimer),
    .rolling_over(timerDone)
  );
  assign { _04_[5:4], _04_[0] } = { noisy, reset, timerDone };
  assign { _05_[5:4], _05_[2:0] } = { reset, _04_[1], noisy, timerDone, _04_[3] };
endmodule

(* hdlname = "\\debounce_top" *)
(* top =  1  *)
(* src = "counter/debounce_top.sv:16.1-75.10" *)
module debounce_top(clk, reset, increment, debouncedOutput, noisyOutput);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  (* src = "counter/debounce_top.sv:34.39-34.45" *)
  wire _030_;
  (* force_downto = 32'd1 *)
  (* src = "counter/debounce_top.sv:50.23-50.39|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6" *)
  wire [6:0] _031_;
  (* force_downto = 32'd1 *)
  (* src = "counter/debounce_top.sv:50.23-50.39|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:112.26-112.27" *)
  wire [6:0] _032_;
  (* force_downto = 32'd1 *)
  (* src = "counter/debounce_top.sv:50.23-50.39|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:170.23-170.24" *)
  (* unused_bits = "0 1 2 4 5 6 7" *)
  wire [7:0] _033_;
  (* force_downto = 32'd1 *)
  (* src = "counter/debounce_top.sv:50.23-50.39|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:168.23-168.24" *)
  (* unused_bits = "7" *)
  wire [7:0] _034_;
  (* force_downto = 32'd1 *)
  (* src = "counter/debounce_top.sv:68.19-68.31|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6" *)
  wire [6:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "counter/debounce_top.sv:68.19-68.31|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:112.26-112.27" *)
  wire [6:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "counter/debounce_top.sv:68.19-68.31|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:170.23-170.24" *)
  (* unused_bits = "0 1 2 4 5 6 7" *)
  wire [7:0] _037_;
  (* force_downto = 32'd1 *)
  (* src = "counter/debounce_top.sv:68.19-68.31|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:168.23-168.24" *)
  (* unused_bits = "7" *)
  wire [7:0] _038_;
  wire _039_;
  wire _040_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire _041_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire _042_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire _043_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _044_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _045_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire _046_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire _047_;
  (* src = "counter/debounce_top.sv:25.19-25.21" *)
  wire F3;
  (* src = "counter/debounce_top.sv:23.16-23.26" *)
  (* unused_bits = "0" *)
  wire [1:0] buttonPush;
  (* src = "counter/debounce_top.sv:17.22-17.25" *)
  input clk;
  wire clk;
  (* src = "counter/debounce_top.sv:26.16-26.30" *)
  (* unused_bits = "0" *)
  wire [6:0] debouncedCount;
  (* src = "counter/debounce_top.sv:18.20-18.35" *)
  output [6:0] debouncedOutput;
  wire [6:0] debouncedOutput;
  (* src = "counter/debounce_top.sv:24.11-24.24" *)
  wire debouncedPush;
  (* src = "counter/debounce_top.sv:17.34-17.43" *)
  input increment;
  wire increment;
  (* src = "counter/debounce_top.sv:26.32-26.42" *)
  (* unused_bits = "0" *)
  wire [6:0] noisyCount;
  (* src = "counter/debounce_top.sv:18.37-18.48" *)
  output [6:0] noisyOutput;
  wire [6:0] noisyOutput;
  (* src = "counter/debounce_top.sv:25.27-25.33" *)
  wire pulse1;
  (* src = "counter/debounce_top.sv:25.35-25.41" *)
  wire pulse2;
  (* src = "counter/debounce_top.sv:17.27-17.32" *)
  input reset;
  wire reset;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _048_ (
    .C(_040_),
    .CE(pulse1),
    .D(_032_[6]),
    .Q(debouncedCount[6]),
    .R(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _049_ (
    .I(_041_),
    .O(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _050_ (
    .I(debouncedCount[6]),
    .O(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _051_ (
    .C(_040_),
    .CE(pulse2),
    .D(_036_[6]),
    .Q(noisyCount[6]),
    .R(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'b1000)
  ) _052_ (
    .I0(_045_[0]),
    .I1(F3),
    .O(pulse2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _053_ (
    .I(_041_),
    .O(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _054_ (
    .I(noisyCount[6]),
    .O(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _055_ (
    .C(_040_),
    .CE(pulse2),
    .D(_036_[0]),
    .Q(_042_),
    .R(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _056_ (
    .I(_041_),
    .O(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _057_ (
    .I(_042_),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _058_ (
    .C(_040_),
    .CE(pulse2),
    .D(_036_[1]),
    .Q(noisyCount[1]),
    .R(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _059_ (
    .I(_041_),
    .O(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _060_ (
    .I(noisyCount[1]),
    .O(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _061_ (
    .C(_040_),
    .CE(pulse2),
    .D(_036_[2]),
    .Q(noisyCount[2]),
    .R(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _062_ (
    .I(_041_),
    .O(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _063_ (
    .I(noisyCount[2]),
    .O(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _064_ (
    .C(_040_),
    .CE(pulse2),
    .D(_036_[3]),
    .Q(noisyCount[3]),
    .R(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _065_ (
    .I(_041_),
    .O(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _066_ (
    .I(noisyCount[3]),
    .O(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _067_ (
    .C(_040_),
    .CE(pulse2),
    .D(_036_[4]),
    .Q(noisyCount[4]),
    .R(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _068_ (
    .I(_041_),
    .O(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _069_ (
    .I(noisyCount[4]),
    .O(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _070_ (
    .C(_040_),
    .CE(pulse2),
    .D(_036_[5]),
    .Q(noisyCount[5]),
    .R(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _071_ (
    .I(_041_),
    .O(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _072_ (
    .I(noisyCount[5]),
    .O(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _073_ (
    .C(_040_),
    .CE(pulse1),
    .D(_032_[0]),
    .Q(_046_),
    .R(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _074_ (
    .I(_041_),
    .O(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _075_ (
    .I(_046_),
    .O(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _076_ (
    .C(_040_),
    .CE(pulse1),
    .D(_032_[1]),
    .Q(debouncedCount[1]),
    .R(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _077_ (
    .I(_041_),
    .O(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _078_ (
    .I(debouncedCount[1]),
    .O(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _079_ (
    .C(_040_),
    .CE(pulse1),
    .D(_032_[2]),
    .Q(debouncedCount[2]),
    .R(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _080_ (
    .I(_041_),
    .O(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _081_ (
    .I(debouncedCount[2]),
    .O(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _082_ (
    .C(_040_),
    .CE(pulse1),
    .D(_032_[3]),
    .Q(debouncedCount[3]),
    .R(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _083_ (
    .I(_041_),
    .O(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _084_ (
    .I(debouncedCount[3]),
    .O(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _085_ (
    .C(_040_),
    .CE(pulse1),
    .D(_032_[4]),
    .Q(debouncedCount[4]),
    .R(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _086_ (
    .I(_041_),
    .O(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _087_ (
    .I(debouncedCount[4]),
    .O(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _088_ (
    .C(_040_),
    .CE(pulse1),
    .D(_032_[5]),
    .Q(debouncedCount[5]),
    .R(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _089_ (
    .I(_041_),
    .O(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _090_ (
    .I(debouncedCount[5]),
    .O(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _091_ (
    .C(_040_),
    .CE(1'b1),
    .D(_028_),
    .Q(_029_),
    .R(1'b0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _092_ (
    .C(_040_),
    .CE(1'b1),
    .D(_029_),
    .Q(buttonPush[1]),
    .R(1'b0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _093_ (
    .C(_040_),
    .CE(1'b1),
    .D(buttonPush[1]),
    .Q(F3),
    .R(1'b0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _094_ (
    .C(_040_),
    .CE(1'b1),
    .D(F3),
    .Q(_043_),
    .R(1'b0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _095_ (
    .C(_040_),
    .CE(1'b1),
    .D(debouncedPush),
    .Q(_044_[1]),
    .R(1'b0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'bx)
  ) _096_ (
    .C(_040_),
    .CE(1'b1),
    .D(_044_[1]),
    .Q(_044_[0]),
    .R(1'b0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'b0100)
  ) _097_ (
    .I0(_044_[0]),
    .I1(_044_[1]),
    .O(pulse1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _098_ (
    .I(_043_),
    .O(_045_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _099_ (
    .I(_041_),
    .O(_030_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  INV _100_ (
    .I(_047_),
    .O(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter/debounce_top.sv:50.23-50.39|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _101_ (
    .CI(1'b0),
    .CO(_031_[3:0]),
    .CYINIT(1'b0),
    .DI(4'b0001),
    .O(_032_[3:0]),
    .S({ debouncedCount[3:1], _017_ })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter/debounce_top.sv:50.23-50.39|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _102_ (
    .CI(_031_[3]),
    .CO({ _033_[7], _031_[6:4] }),
    .CYINIT(1'b0),
    .DI(4'b0000),
    .O({ _034_[7], _032_[6:4] }),
    .S({ 1'b0, debouncedCount[6:4] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter/debounce_top.sv:68.19-68.31|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _103_ (
    .CI(1'b0),
    .CO(_035_[3:0]),
    .CYINIT(1'b0),
    .DI(4'b0001),
    .O(_036_[3:0]),
    .S({ noisyCount[3:1], _005_ })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter/debounce_top.sv:68.19-68.31|/home/jacobb00/yosys/yosys/share/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _104_ (
    .CI(_035_[3]),
    .CO({ _037_[7], _035_[6:4] }),
    .CYINIT(1'b0),
    .DI(4'b0000),
    .O({ _038_[7], _036_[6:4] }),
    .S({ 1'b0, noisyCount[6:4] })
  );
  BUFG _105_ (
    .I(_039_),
    .O(_040_)
  );
  (* keep = 32'd1 *)
  IBUF _106_ (
    .I(clk),
    .O(_039_)
  );
  (* keep = 32'd1 *)
  OBUF _107_ (
    .I(_017_),
    .O(debouncedOutput[0])
  );
  (* keep = 32'd1 *)
  OBUF _108_ (
    .I(_019_),
    .O(debouncedOutput[1])
  );
  (* keep = 32'd1 *)
  OBUF _109_ (
    .I(_021_),
    .O(debouncedOutput[2])
  );
  (* keep = 32'd1 *)
  OBUF _110_ (
    .I(_023_),
    .O(debouncedOutput[3])
  );
  (* keep = 32'd1 *)
  OBUF _111_ (
    .I(_025_),
    .O(debouncedOutput[4])
  );
  (* keep = 32'd1 *)
  OBUF _112_ (
    .I(_027_),
    .O(debouncedOutput[5])
  );
  (* keep = 32'd1 *)
  OBUF _113_ (
    .I(_001_),
    .O(debouncedOutput[6])
  );
  (* keep = 32'd1 *)
  IBUF _114_ (
    .I(increment),
    .O(_047_)
  );
  (* keep = 32'd1 *)
  OBUF _115_ (
    .I(_005_),
    .O(noisyOutput[0])
  );
  (* keep = 32'd1 *)
  OBUF _116_ (
    .I(_007_),
    .O(noisyOutput[1])
  );
  (* keep = 32'd1 *)
  OBUF _117_ (
    .I(_009_),
    .O(noisyOutput[2])
  );
  (* keep = 32'd1 *)
  OBUF _118_ (
    .I(_011_),
    .O(noisyOutput[3])
  );
  (* keep = 32'd1 *)
  OBUF _119_ (
    .I(_013_),
    .O(noisyOutput[4])
  );
  (* keep = 32'd1 *)
  OBUF _120_ (
    .I(_015_),
    .O(noisyOutput[5])
  );
  (* keep = 32'd1 *)
  OBUF _121_ (
    .I(_003_),
    .O(noisyOutput[6])
  );
  (* keep = 32'd1 *)
  IBUF _122_ (
    .I(reset),
    .O(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "counter/debounce_top.sv:34.11-34.95" *)
  debounce debouncer (
    .clk(_040_),
    .debounced(debouncedPush),
    .noisy(buttonPush[1]),
    .reset(_030_)
  );
  assign _045_[1] = F3;
  assign _033_[6:0] = _031_;
  assign _034_[6:0] = _032_;
  assign _037_[6:0] = _035_;
  assign _038_[6:0] = _036_;
endmodule
