/* Generated by Yosys 0.17+41 (git sha1 c525b5f91, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* dynports =  1  *)
(* hdlname = "\\mod_counter" *)
(* src = "../yosys_help_test/counter/mod_counter.sv:17.1-35.10" *)
module \$paramod$af89ed8d08c8018cd41487cbf58ed920a4905fc9\mod_counter (clk, reset, increment, rolling_over, count);
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21" *)
  wire [18:0] _00_;
  wire [18:0] _01_;
  (* src = "../yosys_help_test/counter/mod_counter.sv:33.38-33.62" *)
  wire _02_;
  (* src = "../yosys_help_test/counter/mod_counter.sv:33.25-33.62" *)
  wire _03_;
  (* src = "../yosys_help_test/counter/mod_counter.sv:27.7-27.28" *)
  wire _04_;
  wire [18:0] _05_;
  (* src = "../yosys_help_test/counter/mod_counter.sv:18.19-18.22" *)
  input clk;
  wire clk;
  (* src = "../yosys_help_test/counter/mod_counter.sv:22.36-22.41" *)
  output [18:0] count;
  reg [18:0] count;
  (* src = "../yosys_help_test/counter/mod_counter.sv:20.19-20.28" *)
  input increment;
  wire increment;
  (* src = "../yosys_help_test/counter/mod_counter.sv:19.19-19.24" *)
  input reset;
  wire reset;
  (* src = "../yosys_help_test/counter/mod_counter.sv:21.15-21.27" *)
  output rolling_over;
  wire rolling_over;
  assign _01_ = count + (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20" *) 1'h1;
  assign _02_ = count == (* src = "../yosys_help_test/counter/mod_counter.sv:33.38-33.62" *) 19'h7a120;
  assign _03_ = increment && (* src = "../yosys_help_test/counter/mod_counter.sv:33.25-33.62" *) _02_;
  assign _04_ = reset || (* src = "../yosys_help_test/counter/mod_counter.sv:27.7-27.28" *) rolling_over;
  (* \always_ff  = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21" *)
  always @(posedge clk)
    count <= _00_;
  assign _05_ = increment ? (* src = "../yosys_help_test/counter/mod_counter.sv:29.12-29.21|../yosys_help_test/counter/mod_counter.sv:29.8-30.21" *) _01_ : count;
  assign _00_ = _04_ ? (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/mod_counter.sv:27.7-27.28|../yosys_help_test/counter/mod_counter.sv:27.3-30.21" *) 19'h00000 : _05_;
  assign rolling_over = _03_ ? (* src = "../yosys_help_test/counter/mod_counter.sv:33.24-33.67" *) 1'h1 : 1'h0;
endmodule

(* hdlname = "\\debounce" *)
(* src = "../yosys_help_test/counter/debounce.sv:16.1-93.10" *)
module debounce(clk, reset, noisy, debounced);
  (* src = "../yosys_help_test/counter/debounce.sv:0.0-0.0" *)
  wire [1:0] _00_;
  (* src = "../yosys_help_test/counter/debounce.sv:0.0-0.0" *)
  wire _01_;
  (* src = "../yosys_help_test/counter/debounce.sv:0.0-0.0" *)
  wire _02_;
  (* src = "../yosys_help_test/counter/debounce.sv:0.0-0.0" *)
  wire [1:0] _03_;
  wire _04_;
  (* src = "../yosys_help_test/counter/debounce.sv:0.0-0.0" *)
  wire [1:0] _05_;
  (* src = "../yosys_help_test/counter/debounce.sv:0.0-0.0" *)
  wire [1:0] _06_;
  (* src = "../yosys_help_test/counter/debounce.sv:0.0-0.0" *)
  wire [1:0] _07_;
  wire _08_;
  (* src = "../yosys_help_test/counter/debounce.sv:0.0-0.0" *)
  wire [1:0] _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "../yosys_help_test/counter/debounce.sv:59.34-59.53" *)
  wire _14_;
  (* src = "../yosys_help_test/counter/debounce.sv:61.34-61.52" *)
  wire _15_;
  (* src = "../yosys_help_test/counter/debounce.sv:77.34-77.54" *)
  wire _16_;
  (* src = "../yosys_help_test/counter/debounce.sv:59.43-59.53" *)
  wire _17_;
  (* src = "../yosys_help_test/counter/debounce.sv:77.34-77.40" *)
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  (* src = "../yosys_help_test/counter/debounce.sv:17.19-17.22" *)
  input clk;
  wire clk;
  (* src = "../yosys_help_test/counter/debounce.sv:22.11-22.19" *)
  wire clrTimer;
  (* src = "../yosys_help_test/counter/debounce.sv:25.17-25.22" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18" *)
  wire [18:0] count;
  (* enum_value_00 = "\\s0" *)
  (* enum_value_01 = "\\s1" *)
  (* enum_value_0x = "\\ERR" *)
  (* enum_value_10 = "\\s2" *)
  (* enum_value_11 = "\\s3" *)
  (* src = "../yosys_help_test/counter/debounce.sv:29.18-29.20" *)
  (* wiretype = "\\stateType" *)
  reg [1:0] cs;
  (* src = "../yosys_help_test/counter/debounce.sv:18.18-18.27" *)
  output debounced;
  wire debounced;
  (* src = "../yosys_help_test/counter/debounce.sv:17.31-17.36" *)
  input noisy;
  wire noisy;
  (* enum_value_00 = "\\s0" *)
  (* enum_value_01 = "\\s1" *)
  (* enum_value_0x = "\\ERR" *)
  (* enum_value_10 = "\\s2" *)
  (* enum_value_11 = "\\s3" *)
  (* src = "../yosys_help_test/counter/debounce.sv:29.15-29.17" *)
  (* wiretype = "\\stateType" *)
  wire [1:0] ns;
  (* src = "../yosys_help_test/counter/debounce.sv:17.24-17.29" *)
  input reset;
  wire reset;
  (* src = "../yosys_help_test/counter/debounce.sv:22.21-22.30" *)
  wire timerDone;
  assign _10_ = | { _22_, _21_ };
  assign _11_ = | { _20_, _19_ };
  assign _12_ = | { _21_, _19_ };
  assign _13_ = | { _22_, _20_ };
  assign _14_ = noisy && (* src = "../yosys_help_test/counter/debounce.sv:59.34-59.53" *) _17_;
  assign _15_ = noisy && (* src = "../yosys_help_test/counter/debounce.sv:61.34-61.52" *) timerDone;
  assign _16_ = _18_ && (* src = "../yosys_help_test/counter/debounce.sv:77.34-77.54" *) _17_;
  assign _17_ = ~ (* src = "../yosys_help_test/counter/debounce.sv:59.43-59.53" *) timerDone;
  assign _18_ = ~ (* src = "../yosys_help_test/counter/debounce.sv:77.34-77.40" *) noisy;
  (* \always_ff  = 32'd1 *)
  (* src = "../yosys_help_test/counter/debounce.sv:90.5-91.12" *)
  always @(posedge clk)
    cs <= ns;
  assign _06_ = _14_ ? (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce.sv:59.34-59.53|../yosys_help_test/counter/debounce.sv:59.30-62.37" *) 2'h1 : _07_;
  assign _19_ = cs == (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce.sv:0.0-0.0|../yosys_help_test/counter/debounce.sv:45.13-82.20" *) 1'h1;
  assign _05_ = noisy ? (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce.sv:57.28-57.34|../yosys_help_test/counter/debounce.sv:57.25-62.37" *) _06_ : 2'h0;
  assign _04_ = noisy ? (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce.sv:49.29-49.34|../yosys_help_test/counter/debounce.sv:49.25-52.37" *) 1'h1 : 1'h0;
  assign _20_ = ! (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce.sv:0.0-0.0|../yosys_help_test/counter/debounce.sv:45.13-82.20" *) cs;
  function [1:0] _38_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "../yosys_help_test/counter/debounce.sv:0.0-0.0|../yosys_help_test/counter/debounce.sv:45.13-82.20" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _38_ = b[1:0];
      4'b??1?:
        _38_ = b[3:2];
      4'b?1??:
        _38_ = b[5:4];
      4'b1???:
        _38_ = b[7:6];
      default:
        _38_ = a;
    endcase
  endfunction
  assign _03_ = _38_(2'hx, { 1'h0, _04_, _05_, 1'h1, _08_, _09_ }, { _20_, _19_, _22_, _21_ });
  assign _21_ = cs == (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce.sv:0.0-0.0|../yosys_help_test/counter/debounce.sv:45.13-82.20" *) 2'h3;
  assign _22_ = cs == (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce.sv:0.0-0.0|../yosys_help_test/counter/debounce.sv:45.13-82.20" *) 2'h2;
  function [0:0] _41_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "../yosys_help_test/counter/debounce.sv:0.0-0.0|../yosys_help_test/counter/debounce.sv:45.13-82.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _41_ = b[0:0];
      2'b1?:
        _41_ = b[1:1];
      default:
        _41_ = a;
    endcase
  endfunction
  assign _02_ = _41_(1'hx, 2'h1, { _11_, _10_ });
  function [0:0] _42_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "../yosys_help_test/counter/debounce.sv:0.0-0.0|../yosys_help_test/counter/debounce.sv:45.13-82.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _42_ = b[0:0];
      2'b1?:
        _42_ = b[1:1];
      default:
        _42_ = a;
    endcase
  endfunction
  assign _01_ = _42_(1'hx, 2'h2, { _13_, _12_ });
  assign ns = reset ? (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce.sv:39.7-39.12|../yosys_help_test/counter/debounce.sv:39.3-82.20" *) 2'h0 : _03_;
  assign clrTimer = reset ? (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce.sv:39.7-39.12|../yosys_help_test/counter/debounce.sv:39.3-82.20" *) 1'h0 : _01_;
  assign debounced = reset ? (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce.sv:39.7-39.12|../yosys_help_test/counter/debounce.sv:39.3-82.20" *) 1'h0 : _02_;
  assign _00_ = _16_ ? (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce.sv:77.34-77.54|../yosys_help_test/counter/debounce.sv:77.30-80.37" *) 2'h3 : 2'h0;
  assign _09_ = noisy ? (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce.sv:75.28-75.33|../yosys_help_test/counter/debounce.sv:75.25-80.37" *) 2'h2 : _00_;
  assign _08_ = noisy ? (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce.sv:67.25-67.30|../yosys_help_test/counter/debounce.sv:67.21-70.33" *) 1'h0 : 1'h1;
  assign _07_ = _15_ ? (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce.sv:61.34-61.52|../yosys_help_test/counter/debounce.sv:61.30-62.37" *) 2'h2 : 2'b0x;
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/debounce.sv:86.31-86.121" *)
  \$paramod$af89ed8d08c8018cd41487cbf58ed920a4905fc9\mod_counter  timer (
    .clk(clk),
    .count(count),
    .increment(1'h1),
    .reset(clrTimer),
    .rolling_over(timerDone)
  );
endmodule

(* hdlname = "\\debounce_top" *)
(* top =  1  *)
(* src = "../yosys_help_test/counter/debounce_top.sv:16.1-75.10" *)
module debounce_top(clk, reset, increment, debouncedOutput, noisyOutput);
  (* src = "../yosys_help_test/counter/debounce_top.sv:29.5-30.37" *)
  wire _00_;
  (* src = "../yosys_help_test/counter/debounce_top.sv:44.5-52.7" *)
  wire [6:0] _01_;
  (* src = "../yosys_help_test/counter/debounce_top.sv:62.5-70.16" *)
  wire [6:0] _02_;
  wire [6:0] _03_;
  (* src = "../yosys_help_test/counter/debounce_top.sv:68.19-68.31" *)
  (* unused_bits = "7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _04_;
  (* src = "../yosys_help_test/counter/debounce_top.sv:34.39-34.45" *)
  wire _05_;
  (* src = "../yosys_help_test/counter/debounce_top.sv:41.22-41.25" *)
  wire _06_;
  (* src = "../yosys_help_test/counter/debounce_top.sv:59.22-59.25" *)
  wire _07_;
  wire [6:0] _08_;
  wire [6:0] _09_;
  (* src = "../yosys_help_test/counter/debounce_top.sv:25.11-25.13" *)
  reg F1;
  (* src = "../yosys_help_test/counter/debounce_top.sv:25.15-25.17" *)
  reg F2;
  (* src = "../yosys_help_test/counter/debounce_top.sv:25.19-25.21" *)
  reg F3;
  (* src = "../yosys_help_test/counter/debounce_top.sv:25.23-25.25" *)
  reg F4;
  (* src = "../yosys_help_test/counter/debounce_top.sv:23.16-23.26" *)
  reg [1:0] buttonPush;
  (* src = "../yosys_help_test/counter/debounce_top.sv:17.22-17.25" *)
  input clk;
  wire clk;
  (* src = "../yosys_help_test/counter/debounce_top.sv:26.16-26.30" *)
  reg [6:0] debouncedCount;
  (* src = "../yosys_help_test/counter/debounce_top.sv:18.20-18.35" *)
  output [6:0] debouncedOutput;
  wire [6:0] debouncedOutput;
  (* src = "../yosys_help_test/counter/debounce_top.sv:24.11-24.24" *)
  wire debouncedPush;
  (* src = "../yosys_help_test/counter/debounce_top.sv:17.34-17.43" *)
  input increment;
  wire increment;
  (* src = "../yosys_help_test/counter/debounce_top.sv:26.32-26.42" *)
  reg [6:0] noisyCount;
  (* src = "../yosys_help_test/counter/debounce_top.sv:18.37-18.48" *)
  output [6:0] noisyOutput;
  wire [6:0] noisyOutput;
  (* src = "../yosys_help_test/counter/debounce_top.sv:25.27-25.33" *)
  wire pulse1;
  (* src = "../yosys_help_test/counter/debounce_top.sv:25.35-25.41" *)
  wire pulse2;
  (* src = "../yosys_help_test/counter/debounce_top.sv:17.27-17.32" *)
  input reset;
  wire reset;
  assign _03_ = debouncedCount + (* src = "../yosys_help_test/counter/debounce_top.sv:50.23-50.39" *) 1'h1;
  assign _04_[6:0] = noisyCount + (* src = "../yosys_help_test/counter/debounce_top.sv:68.19-68.31" *) 1'h1;
  assign pulse1 = _06_ && (* src = "../yosys_help_test/counter/debounce_top.sv:41.22-41.31" *) F1;
  assign pulse2 = _07_ && (* src = "../yosys_help_test/counter/debounce_top.sv:59.22-59.31" *) F3;
  assign _00_ = ~ (* src = "../yosys_help_test/counter/debounce_top.sv:30.26-30.36" *) increment;
  assign _05_ = ~ (* src = "../yosys_help_test/counter/debounce_top.sv:34.39-34.45" *) reset;
  assign _06_ = ~ (* src = "../yosys_help_test/counter/debounce_top.sv:41.22-41.25" *) F2;
  assign _07_ = ~ (* src = "../yosys_help_test/counter/debounce_top.sv:59.22-59.25" *) F4;
  assign debouncedOutput = ~ (* src = "../yosys_help_test/counter/debounce_top.sv:71.27-71.42" *) debouncedCount;
  assign noisyOutput = ~ (* src = "../yosys_help_test/counter/debounce_top.sv:72.23-72.34" *) noisyCount;
  (* \always_ff  = 32'd1 *)
  (* src = "../yosys_help_test/counter/debounce_top.sv:62.5-70.16" *)
  always @(posedge clk)
    noisyCount <= _02_;
  (* \always_ff  = 32'd1 *)
  (* src = "../yosys_help_test/counter/debounce_top.sv:57.5-58.18" *)
  always @(posedge clk)
    F4 <= F3;
  (* \always_ff  = 32'd1 *)
  (* src = "../yosys_help_test/counter/debounce_top.sv:55.5-56.29" *)
  always @(posedge clk)
    F3 <= buttonPush[1];
  (* \always_ff  = 32'd1 *)
  (* src = "../yosys_help_test/counter/debounce_top.sv:44.5-52.7" *)
  always @(posedge clk)
    debouncedCount <= _01_;
  (* \always_ff  = 32'd1 *)
  (* src = "../yosys_help_test/counter/debounce_top.sv:39.5-40.18" *)
  always @(posedge clk)
    F2 <= F1;
  (* \always_ff  = 32'd1 *)
  (* src = "../yosys_help_test/counter/debounce_top.sv:37.5-38.29" *)
  always @(posedge clk)
    F1 <= debouncedPush;
  (* \always_ff  = 32'd1 *)
  (* src = "../yosys_help_test/counter/debounce_top.sv:31.5-32.40" *)
  always @(posedge clk)
    buttonPush[1] <= buttonPush[0];
  (* \always_ff  = 32'd1 *)
  (* src = "../yosys_help_test/counter/debounce_top.sv:29.5-30.37" *)
  always @(posedge clk)
    buttonPush[0] <= _00_;
  assign _08_ = pulse2 ? (* src = "../yosys_help_test/counter/debounce_top.sv:66.18-66.24|../yosys_help_test/counter/debounce_top.sv:66.14-70.16" *) _04_[6:0] : noisyCount;
  assign _02_ = reset ? (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce_top.sv:63.13-63.19|../yosys_help_test/counter/debounce_top.sv:63.9-70.16" *) _08_ : 7'h00;
  assign _09_ = pulse1 ? (* src = "../yosys_help_test/counter/debounce_top.sv:48.12-48.18|../yosys_help_test/counter/debounce_top.sv:48.8-52.7" *) _03_ : debouncedCount;
  assign _01_ = reset ? (* full_case = 32'd1 *) (* src = "../yosys_help_test/counter/debounce_top.sv:45.7-45.13|../yosys_help_test/counter/debounce_top.sv:45.3-52.7" *) _09_ : 7'h00;
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/debounce_top.sv:34.11-34.95" *)
  debounce debouncer (
    .clk(clk),
    .debounced(debouncedPush),
    .noisy(buttonPush[1]),
    .reset(_05_)
  );
endmodule
