/* Generated by Yosys 0.17+41 (git sha1 c525b5f91, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* dynports =  1  *)
(* blackbox =  1  *)
(* hdlname = "\\mod_counter" *)
(* src = "counter/mod_counter.sv:17.1-35.10" *)
module \$paramod$af89ed8d08c8018cd41487cbf58ed920a4905fc9\mod_counter (clk, reset, increment, rolling_over, count);
  (* src = "counter/mod_counter.sv:18.19-18.22" *)
  input clk;
  wire clk;
  (* src = "counter/mod_counter.sv:22.36-22.41" *)
  output [18:0] count;
  wire [18:0] count;
  (* src = "counter/mod_counter.sv:20.19-20.28" *)
  input increment;
  wire increment;
  (* src = "counter/mod_counter.sv:19.19-19.24" *)
  input reset;
  wire reset;
  (* src = "counter/mod_counter.sv:21.15-21.27" *)
  output rolling_over;
  wire rolling_over;
endmodule
