/* Generated by Yosys 0.17+41 (git sha1 c525b5f91, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
module \$paramod$af89ed8d08c8018cd41487cbf58ed920a4905fc9\mod_counter (clk_copy_2, reset_copy_0, reset_copy_2, rolling_over_copy_2, rolling_over_copy_1, rolling_over_copy_0, reset_copy_1, clk_copy_1, increment_copy_2, increment_copy_1, increment_copy_0, clk_copy_0, count_copy_0, count_copy_2, count_copy_1);
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [6:0] _000_;
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:78.16-78.18" *)
  wire _001_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [7:0] _002_;
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:84.12-84.14" *)
  wire _003_;
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:84.16-84.18" *)
  wire _004_;
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:86.46-86.71|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:78.16-78.18" *)
  wire _005_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [7:0] _006_;
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:84.12-84.14" *)
  wire _007_;
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:84.16-84.18" *)
  wire _008_;
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:86.46-86.71|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:78.16-78.18" *)
  wire _009_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [6:0] _010_;
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:78.16-78.18" *)
  wire _011_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [6:0] _012_;
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:78.16-78.18" *)
  wire _013_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [6:0] _014_;
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:78.12-78.14" *)
  wire _015_;
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:78.16-78.18" *)
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _046_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _047_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _048_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _049_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _050_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _051_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _052_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _053_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _054_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _055_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _056_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _057_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _058_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _059_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [2:0] _060_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _061_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _062_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _063_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _064_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _065_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _066_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _067_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _068_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _069_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _070_;
  (* force_downto = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _071_;
  (* src = "../yosys_help_test/counter/mod_counter.sv:27.7-27.28" *)
  wire \$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_0 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:27.7-27.28" *)
  wire \$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_1 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:27.7-27.28" *)
  wire \$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_2 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[10]_copy_0 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[10]_copy_1 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[10]_copy_2 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[11]_copy_0 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[11]_copy_1 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[11]_copy_2 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[13]_copy_0 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[13]_copy_1 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[13]_copy_2 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[14]_copy_0 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[15]_copy_0 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[15]_copy_1 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[15]_copy_2 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[16]_copy_0 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[16]_copy_1 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[16]_copy_2 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[17]_copy_0 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[17]_copy_1 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[17]_copy_2 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[18]_copy_0 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[18]_copy_1 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[18]_copy_2 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[3]_copy_0 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[3]_copy_1 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[3]_copy_2 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[4]_copy_0 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[4]_copy_1 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[4]_copy_2 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[5]_copy_0 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[5]_copy_1 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[5]_copy_2 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[7]_copy_1 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[7]_copy_2 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[8]_copy_0 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[9]_copy_0 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[9]_copy_1 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:30.13-30.20|/home/jacobb00/yosys/yosys/share/techmap.v:270.26-270.27" *)
  wire \$auto$alumacc.cc:485:replace_alu$256.Y[9]_copy_2 ;
  (* src = "../yosys_help_test/counter/mod_counter.sv:18.19-18.22" *)
  input clk_copy_0;
  wire clk_copy_0;
  (* src = "../yosys_help_test/counter/mod_counter.sv:18.19-18.22" *)
  input clk_copy_1;
  wire clk_copy_1;
  (* src = "../yosys_help_test/counter/mod_counter.sv:18.19-18.22" *)
  input clk_copy_2;
  wire clk_copy_2;
  (* src = "../yosys_help_test/counter/mod_counter.sv:22.36-22.41" *)
  output [18:0] count_copy_0;
  wire [18:0] count_copy_0;
  (* src = "../yosys_help_test/counter/mod_counter.sv:22.36-22.41" *)
  output [18:0] count_copy_1;
  wire [18:0] count_copy_1;
  (* src = "../yosys_help_test/counter/mod_counter.sv:22.36-22.41" *)
  output [18:0] count_copy_2;
  wire [18:0] count_copy_2;
  (* src = "../yosys_help_test/counter/mod_counter.sv:20.19-20.28" *)
  input increment_copy_0;
  wire increment_copy_0;
  (* src = "../yosys_help_test/counter/mod_counter.sv:20.19-20.28" *)
  input increment_copy_1;
  wire increment_copy_1;
  (* src = "../yosys_help_test/counter/mod_counter.sv:20.19-20.28" *)
  input increment_copy_2;
  wire increment_copy_2;
  (* src = "../yosys_help_test/counter/mod_counter.sv:19.19-19.24" *)
  input reset_copy_0;
  wire reset_copy_0;
  (* src = "../yosys_help_test/counter/mod_counter.sv:19.19-19.24" *)
  input reset_copy_1;
  wire reset_copy_1;
  (* src = "../yosys_help_test/counter/mod_counter.sv:19.19-19.24" *)
  input reset_copy_2;
  wire reset_copy_2;
  (* src = "../yosys_help_test/counter/mod_counter.sv:21.15-21.27" *)
  output rolling_over_copy_0;
  wire rolling_over_copy_0;
  (* src = "../yosys_help_test/counter/mod_counter.sv:21.15-21.27" *)
  output rolling_over_copy_1;
  wire rolling_over_copy_1;
  (* src = "../yosys_help_test/counter/mod_counter.sv:21.15-21.27" *)
  output rolling_over_copy_2;
  wire rolling_over_copy_2;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _072_ (
    .I0(_051_[0]),
    .I1(_051_[1]),
    .O(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h1000000000000000)
  ) _073_ (
    .I0(_014_[2]),
    .I1(_014_[4]),
    .I2(_014_[1]),
    .I3(_014_[3]),
    .I4(_050_[4]),
    .I5(_014_[5]),
    .O(_051_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _074_ (
    .I0(_049_[0]),
    .I1(_049_[1]),
    .O(_014_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _075_ (
    .I0(_000_[0]),
    .I1(_000_[1]),
    .O(_050_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h1000000000000000)
  ) _076_ (
    .I0(_000_[2]),
    .I1(_000_[3]),
    .I2(_014_[6]),
    .I3(_048_[3]),
    .I4(_048_[4]),
    .I5(_048_[5]),
    .O(_051_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0100)
  ) _077_ (
    .I0(_047_[0]),
    .I1(_047_[1]),
    .I2(_047_[2]),
    .I3(_047_[3]),
    .O(_048_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0100)
  ) _078_ (
    .I0(_000_[4]),
    .I1(_000_[6]),
    .I2(_046_[2]),
    .I3(_000_[5]),
    .O(_048_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _079_ (
    .I0(_054_[0]),
    .I1(_054_[1]),
    .O(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h1000000000000000)
  ) _080_ (
    .I0(_010_[3]),
    .I1(_052_[1]),
    .I2(_052_[2]),
    .I3(_010_[4]),
    .I4(_052_[4]),
    .I5(_052_[5]),
    .O(_054_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _081_ (
    .I0(_002_[0]),
    .I1(_002_[1]),
    .O(_052_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _082_ (
    .I0(_010_[1]),
    .I1(_010_[2]),
    .O(_052_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h8000000000000000)
  ) _083_ (
    .I0(_053_[0]),
    .I1(_053_[1]),
    .I2(_053_[2]),
    .I3(_053_[3]),
    .I4(_053_[4]),
    .I5(_053_[5]),
    .O(_054_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0100)
  ) _084_ (
    .I0(_002_[6]),
    .I1(_002_[7]),
    .I2(_010_[6]),
    .I3(_010_[5]),
    .O(_053_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0100)
  ) _085_ (
    .I0(_002_[2]),
    .I1(_002_[3]),
    .I2(_002_[4]),
    .I3(_002_[5]),
    .O(_053_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _086_ (
    .I0(_057_[0]),
    .I1(_057_[1]),
    .O(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h1000000000000000)
  ) _087_ (
    .I0(_012_[3]),
    .I1(_055_[1]),
    .I2(_055_[2]),
    .I3(_012_[4]),
    .I4(_055_[4]),
    .I5(_055_[5]),
    .O(_057_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _088_ (
    .I0(_006_[0]),
    .I1(_006_[1]),
    .O(_055_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _089_ (
    .I0(_012_[1]),
    .I1(_012_[2]),
    .O(_055_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h8000000000000000)
  ) _090_ (
    .I0(_056_[0]),
    .I1(_056_[1]),
    .I2(_056_[2]),
    .I3(_056_[3]),
    .I4(_056_[4]),
    .I5(_056_[5]),
    .O(_057_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0100)
  ) _091_ (
    .I0(_006_[6]),
    .I1(_006_[7]),
    .I2(_012_[6]),
    .I3(_012_[5]),
    .O(_056_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0100)
  ) _092_ (
    .I0(_006_[2]),
    .I1(_006_[3]),
    .I2(_006_[4]),
    .I3(_006_[5]),
    .O(_056_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hf8)
  ) _093_ (
    .I0(_051_[1]),
    .I1(_051_[0]),
    .I2(_058_[2]),
    .O(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_0 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hf8)
  ) _094_ (
    .I0(_054_[1]),
    .I1(_054_[0]),
    .I2(_059_[2]),
    .O(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hf8)
  ) _095_ (
    .I0(_057_[1]),
    .I1(_057_[0]),
    .I2(_060_[2]),
    .O(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _096_ (
    .I0(_000_[0]),
    .I1(_000_[1]),
    .O(_061_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _097_ (
    .I0(_002_[0]),
    .I1(_002_[1]),
    .O(_062_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _098_ (
    .I0(_006_[0]),
    .I1(_006_[1]),
    .O(_063_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h78)
  ) _099_ (
    .I0(_061_[0]),
    .I1(_000_[2]),
    .I2(_000_[3]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[3]_copy_0 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h78)
  ) _100_ (
    .I0(_062_[0]),
    .I1(_002_[2]),
    .I2(_002_[3]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[3]_copy_1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h78)
  ) _101_ (
    .I0(_063_[0]),
    .I1(_006_[2]),
    .I2(_006_[3]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[3]_copy_2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h7f80)
  ) _102_ (
    .I0(_061_[0]),
    .I1(_000_[2]),
    .I2(_000_[3]),
    .I3(_000_[4]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[4]_copy_0 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h7f80)
  ) _103_ (
    .I0(_062_[0]),
    .I1(_002_[2]),
    .I2(_002_[3]),
    .I3(_002_[4]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[4]_copy_1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h7f80)
  ) _104_ (
    .I0(_063_[0]),
    .I1(_006_[2]),
    .I2(_006_[3]),
    .I3(_006_[4]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[4]_copy_2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147450880)
  ) _105_ (
    .I0(_061_[0]),
    .I1(_000_[2]),
    .I2(_000_[3]),
    .I3(_000_[4]),
    .I4(_000_[5]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[5]_copy_0 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147450880)
  ) _106_ (
    .I0(_062_[0]),
    .I1(_002_[2]),
    .I2(_002_[3]),
    .I3(_002_[4]),
    .I4(_002_[5]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[5]_copy_1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147450880)
  ) _107_ (
    .I0(_063_[0]),
    .I1(_006_[2]),
    .I2(_006_[3]),
    .I3(_006_[4]),
    .I4(_006_[5]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[5]_copy_2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147483648)
  ) _108_ (
    .I0(_061_[0]),
    .I1(_000_[2]),
    .I2(_000_[3]),
    .I3(_000_[4]),
    .I4(_000_[5]),
    .O(_064_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147483648)
  ) _109_ (
    .I0(_062_[0]),
    .I1(_002_[2]),
    .I2(_002_[3]),
    .I3(_002_[4]),
    .I4(_002_[5]),
    .O(_065_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147483648)
  ) _110_ (
    .I0(_063_[0]),
    .I1(_006_[2]),
    .I2(_006_[3]),
    .I3(_006_[4]),
    .I4(_006_[5]),
    .O(_066_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:80.45-80.70|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h8000000000000000)
  ) _111_ (
    .I0(_000_[0]),
    .I1(_000_[1]),
    .I2(_000_[2]),
    .I3(_000_[3]),
    .I4(_000_[4]),
    .I5(_000_[5]),
    .O(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _112_ (
    .I0(1'h0),
    .I1(_001_),
    .O(_067_[0]),
    .S(_000_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h78)
  ) _113_ (
    .I0(_065_[0]),
    .I1(_002_[6]),
    .I2(_002_[7]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[7]_copy_1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h78)
  ) _114_ (
    .I0(_066_[0]),
    .I1(_006_[6]),
    .I2(_006_[7]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[7]_copy_2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h78)
  ) _115_ (
    .I0(_067_[0]),
    .I1(_046_[2]),
    .I2(_047_[3]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[8]_copy_0 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:85.46-85.71|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _116_ (
    .I0(1'h0),
    .I1(1'h0),
    .O(_003_),
    .S(_002_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:86.46-86.71|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:80.45-80.70|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h8000000000000000)
  ) _117_ (
    .I0(_002_[0]),
    .I1(_002_[1]),
    .I2(_002_[2]),
    .I3(_002_[3]),
    .I4(_002_[4]),
    .I5(_002_[5]),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:86.46-86.71|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _118_ (
    .I0(1'h0),
    .I1(_005_),
    .O(_004_),
    .S(_002_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:87.13-87.52" *)
  MUXF8 _119_ (
    .I0(_003_),
    .I1(_004_),
    .O(_010_[0]),
    .S(_002_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:85.46-85.71|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _120_ (
    .I0(1'h0),
    .I1(1'h0),
    .O(_007_),
    .S(_006_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:86.46-86.71|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:80.45-80.70|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h8000000000000000)
  ) _121_ (
    .I0(_006_[0]),
    .I1(_006_[1]),
    .I2(_006_[2]),
    .I3(_006_[3]),
    .I4(_006_[4]),
    .I5(_006_[5]),
    .O(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:86.46-86.71|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _122_ (
    .I0(1'h0),
    .I1(_009_),
    .O(_008_),
    .S(_006_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:87.13-87.52" *)
  MUXF8 _123_ (
    .I0(_007_),
    .I1(_008_),
    .O(_012_[0]),
    .S(_006_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h7f80)
  ) _124_ (
    .I0(_067_[0]),
    .I1(_046_[2]),
    .I2(_047_[3]),
    .I3(_047_[0]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[9]_copy_0 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h78)
  ) _125_ (
    .I0(_010_[0]),
    .I1(_010_[5]),
    .I2(_010_[6]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[9]_copy_1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h78)
  ) _126_ (
    .I0(_012_[0]),
    .I1(_012_[5]),
    .I2(_012_[6]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[9]_copy_2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147450880)
  ) _127_ (
    .I0(_067_[0]),
    .I1(_046_[2]),
    .I2(_047_[3]),
    .I3(_047_[0]),
    .I4(_047_[1]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[10]_copy_0 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h7f80)
  ) _128_ (
    .I0(_010_[0]),
    .I1(_010_[5]),
    .I2(_010_[6]),
    .I3(_010_[2]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[10]_copy_1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h7f80)
  ) _129_ (
    .I0(_012_[0]),
    .I1(_012_[5]),
    .I2(_012_[6]),
    .I3(_012_[2]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[10]_copy_2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h7fffffff80000000)
  ) _130_ (
    .I0(_067_[0]),
    .I1(_046_[2]),
    .I2(_047_[3]),
    .I3(_047_[0]),
    .I4(_047_[1]),
    .I5(_047_[2]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[11]_copy_0 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147450880)
  ) _131_ (
    .I0(_010_[0]),
    .I1(_010_[2]),
    .I2(_010_[5]),
    .I3(_010_[6]),
    .I4(_010_[1]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[11]_copy_1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147450880)
  ) _132_ (
    .I0(_012_[0]),
    .I1(_012_[2]),
    .I2(_012_[5]),
    .I3(_012_[6]),
    .I4(_012_[1]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[11]_copy_2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h8000000000000000)
  ) _133_ (
    .I0(_067_[0]),
    .I1(_046_[2]),
    .I2(_047_[3]),
    .I3(_047_[0]),
    .I4(_047_[1]),
    .I5(_047_[2]),
    .O(_014_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147483648)
  ) _134_ (
    .I0(_010_[0]),
    .I1(_010_[1]),
    .I2(_010_[2]),
    .I3(_010_[5]),
    .I4(_010_[6]),
    .O(_068_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147483648)
  ) _135_ (
    .I0(_012_[0]),
    .I1(_012_[1]),
    .I2(_012_[2]),
    .I3(_012_[5]),
    .I4(_012_[6]),
    .O(_069_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h78)
  ) _136_ (
    .I0(_014_[0]),
    .I1(_014_[2]),
    .I2(_014_[3]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[13]_copy_0 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h78)
  ) _137_ (
    .I0(_068_[0]),
    .I1(_010_[3]),
    .I2(_010_[4]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[13]_copy_1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h78)
  ) _138_ (
    .I0(_069_[0]),
    .I1(_012_[3]),
    .I2(_012_[4]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[13]_copy_2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h7f80)
  ) _139_ (
    .I0(_014_[0]),
    .I1(_014_[2]),
    .I2(_014_[3]),
    .I3(_014_[4]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[14]_copy_0 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:80.45-80.70|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h8000000000000000)
  ) _140_ (
    .I0(_010_[0]),
    .I1(_010_[1]),
    .I2(_010_[2]),
    .I3(_010_[3]),
    .I4(_010_[4]),
    .I5(_010_[5]),
    .O(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _141_ (
    .I0(1'h0),
    .I1(_011_),
    .O(_070_[0]),
    .S(_010_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:80.45-80.70|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h8000000000000000)
  ) _142_ (
    .I0(_012_[0]),
    .I1(_012_[1]),
    .I2(_012_[2]),
    .I3(_012_[3]),
    .I4(_012_[4]),
    .I5(_012_[5]),
    .O(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _143_ (
    .I0(1'h0),
    .I1(_013_),
    .O(_071_[0]),
    .S(_012_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147450880)
  ) _144_ (
    .I0(_014_[0]),
    .I1(_014_[2]),
    .I2(_014_[3]),
    .I3(_014_[4]),
    .I4(_049_[0]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[15]_copy_0 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h78)
  ) _145_ (
    .I0(_070_[0]),
    .I1(_052_[1]),
    .I2(_052_[5]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[15]_copy_1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h78)
  ) _146_ (
    .I0(_071_[0]),
    .I1(_055_[1]),
    .I2(_055_[5]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[15]_copy_2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h7fffffff80000000)
  ) _147_ (
    .I0(_014_[0]),
    .I1(_014_[2]),
    .I2(_014_[3]),
    .I3(_014_[4]),
    .I4(_049_[0]),
    .I5(_049_[1]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[16]_copy_0 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h7f80)
  ) _148_ (
    .I0(_070_[0]),
    .I1(_052_[1]),
    .I2(_052_[5]),
    .I3(_053_[3]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[16]_copy_1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h7f80)
  ) _149_ (
    .I0(_071_[0]),
    .I1(_055_[1]),
    .I2(_055_[5]),
    .I3(_056_[3]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[16]_copy_2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h7fffffff80000000)
  ) _150_ (
    .I0(_014_[0]),
    .I1(_014_[1]),
    .I2(_014_[2]),
    .I3(_014_[3]),
    .I4(_014_[4]),
    .I5(_014_[5]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[17]_copy_0 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147450880)
  ) _151_ (
    .I0(_070_[0]),
    .I1(_052_[1]),
    .I2(_052_[5]),
    .I3(_053_[3]),
    .I4(_053_[2]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[17]_copy_1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147450880)
  ) _152_ (
    .I0(_071_[0]),
    .I1(_055_[1]),
    .I2(_055_[5]),
    .I3(_056_[3]),
    .I4(_056_[2]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[17]_copy_2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:79.45-79.70|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h8000000000000000)
  ) _153_ (
    .I0(_014_[0]),
    .I1(_014_[1]),
    .I2(_014_[2]),
    .I3(_014_[3]),
    .I4(_014_[4]),
    .I5(_014_[5]),
    .O(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:80.45-80.70|/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h7fffffffffffffff)
  ) _154_ (
    .I0(_014_[0]),
    .I1(_014_[1]),
    .I2(_014_[2]),
    .I3(_014_[3]),
    .I4(_014_[4]),
    .I5(_014_[5]),
    .O(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:81.13-81.52" *)
  MUXF7 _155_ (
    .I0(_015_),
    .I1(_016_),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[18]_copy_0 ),
    .S(_014_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h7fffffff80000000)
  ) _156_ (
    .I0(_070_[0]),
    .I1(_052_[1]),
    .I2(_052_[5]),
    .I3(_053_[2]),
    .I4(_053_[3]),
    .I5(_053_[4]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[18]_copy_1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h7fffffff80000000)
  ) _157_ (
    .I0(_071_[0]),
    .I1(_055_[1]),
    .I2(_055_[5]),
    .I3(_056_[2]),
    .I4(_056_[3]),
    .I5(_056_[4]),
    .O(\$auto$alumacc.cc:485:replace_alu$256.Y[18]_copy_2 )
  );
  BUFG _158_ (
    .I(_020_),
    .O(_043_)
  );
  BUFG _159_ (
    .I(_021_),
    .O(_044_)
  );
  BUFG _160_ (
    .I(_022_),
    .O(_045_)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _161_ (
    .C(_043_),
    .CE(1'h1),
    .D(_033_),
    .Q(_000_[1]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _162_ (
    .C(_044_),
    .CE(1'h1),
    .D(_034_),
    .Q(_002_[1]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _163_ (
    .C(_045_),
    .CE(1'h1),
    .D(_028_),
    .Q(_006_[1]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _164_ (
    .C(_043_),
    .CE(1'h1),
    .D(_030_),
    .Q(_000_[0]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _165_ (
    .C(_044_),
    .CE(1'h1),
    .D(_037_),
    .Q(_002_[0]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _166_ (
    .C(_045_),
    .CE(1'h1),
    .D(_031_),
    .Q(_006_[0]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _167_ (
    .C(_043_),
    .CE(1'h1),
    .D(_036_),
    .Q(_000_[2]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _168_ (
    .C(_044_),
    .CE(1'h1),
    .D(_026_),
    .Q(_002_[2]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _169_ (
    .C(_045_),
    .CE(1'h1),
    .D(_024_),
    .Q(_006_[2]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _170_ (
    .C(_043_),
    .CE(_048_[3]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[3]_copy_0 ),
    .Q(_000_[3]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_0 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _171_ (
    .C(_044_),
    .CE(_053_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[3]_copy_1 ),
    .Q(_002_[3]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_1 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _172_ (
    .C(_045_),
    .CE(_056_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[3]_copy_2 ),
    .Q(_006_[3]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_2 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _173_ (
    .C(_043_),
    .CE(_048_[3]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[4]_copy_0 ),
    .Q(_000_[4]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_0 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _174_ (
    .C(_044_),
    .CE(_053_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[4]_copy_1 ),
    .Q(_002_[4]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_1 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _175_ (
    .C(_045_),
    .CE(_056_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[4]_copy_2 ),
    .Q(_006_[4]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_2 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _176_ (
    .C(_043_),
    .CE(_048_[3]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[5]_copy_0 ),
    .Q(_000_[5]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_0 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _177_ (
    .C(_044_),
    .CE(_053_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[5]_copy_1 ),
    .Q(_002_[5]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_1 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _178_ (
    .C(_045_),
    .CE(_056_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[5]_copy_2 ),
    .Q(_006_[5]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_2 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _179_ (
    .C(_043_),
    .CE(1'h1),
    .D(_023_),
    .Q(_000_[6]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _180_ (
    .C(_044_),
    .CE(1'h1),
    .D(_027_),
    .Q(_002_[6]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _181_ (
    .C(_045_),
    .CE(1'h1),
    .D(_029_),
    .Q(_006_[6]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _182_ (
    .C(_043_),
    .CE(1'h1),
    .D(_025_),
    .Q(_046_[2]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _183_ (
    .C(_044_),
    .CE(_053_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[7]_copy_1 ),
    .Q(_002_[7]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_1 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _184_ (
    .C(_045_),
    .CE(_056_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[7]_copy_2 ),
    .Q(_006_[7]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_2 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _185_ (
    .C(_043_),
    .CE(_048_[3]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[8]_copy_0 ),
    .Q(_047_[3]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_0 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _186_ (
    .C(_044_),
    .CE(1'h1),
    .D(_035_),
    .Q(_010_[5]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _187_ (
    .C(_045_),
    .CE(1'h1),
    .D(_032_),
    .Q(_012_[5]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _188_ (
    .C(_043_),
    .CE(_048_[3]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[9]_copy_0 ),
    .Q(_047_[0]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_0 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _189_ (
    .C(_044_),
    .CE(_053_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[9]_copy_1 ),
    .Q(_010_[6]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_1 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _190_ (
    .C(_045_),
    .CE(_056_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[9]_copy_2 ),
    .Q(_012_[6]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_2 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _191_ (
    .C(_043_),
    .CE(_048_[3]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[10]_copy_0 ),
    .Q(_047_[1]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_0 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _192_ (
    .C(_044_),
    .CE(_053_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[10]_copy_1 ),
    .Q(_010_[2]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_1 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _193_ (
    .C(_045_),
    .CE(_056_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[10]_copy_2 ),
    .Q(_012_[2]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_2 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _194_ (
    .C(_043_),
    .CE(_048_[3]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[11]_copy_0 ),
    .Q(_047_[2]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_0 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _195_ (
    .C(_044_),
    .CE(_053_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[11]_copy_1 ),
    .Q(_010_[1]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_1 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _196_ (
    .C(_045_),
    .CE(_056_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[11]_copy_2 ),
    .Q(_012_[1]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_2 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _197_ (
    .C(_043_),
    .CE(1'h1),
    .D(_040_),
    .Q(_014_[2]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _198_ (
    .C(_044_),
    .CE(1'h1),
    .D(_041_),
    .Q(_010_[3]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _199_ (
    .C(_045_),
    .CE(1'h1),
    .D(_042_),
    .Q(_012_[3]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _200_ (
    .C(_043_),
    .CE(_048_[3]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[13]_copy_0 ),
    .Q(_014_[3]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_0 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _201_ (
    .C(_044_),
    .CE(_053_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[13]_copy_1 ),
    .Q(_010_[4]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_1 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _202_ (
    .C(_045_),
    .CE(_056_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[13]_copy_2 ),
    .Q(_012_[4]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_2 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _203_ (
    .C(_043_),
    .CE(_048_[3]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[14]_copy_0 ),
    .Q(_014_[4]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_0 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _204_ (
    .C(_044_),
    .CE(1'h1),
    .D(_038_),
    .Q(_052_[1]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _205_ (
    .C(_045_),
    .CE(1'h1),
    .D(_039_),
    .Q(_055_[1]),
    .R(1'h0)
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _206_ (
    .C(_043_),
    .CE(_048_[3]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[15]_copy_0 ),
    .Q(_049_[0]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_0 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _207_ (
    .C(_044_),
    .CE(_053_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[15]_copy_1 ),
    .Q(_052_[5]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_1 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _208_ (
    .C(_045_),
    .CE(_056_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[15]_copy_2 ),
    .Q(_055_[5]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_2 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _209_ (
    .C(_043_),
    .CE(_048_[3]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[16]_copy_0 ),
    .Q(_049_[1]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_0 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _210_ (
    .C(_044_),
    .CE(_053_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[16]_copy_1 ),
    .Q(_053_[3]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_1 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _211_ (
    .C(_045_),
    .CE(_056_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[16]_copy_2 ),
    .Q(_056_[3]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_2 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _212_ (
    .C(_043_),
    .CE(_048_[3]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[17]_copy_0 ),
    .Q(_014_[5]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_0 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _213_ (
    .C(_044_),
    .CE(_053_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[17]_copy_1 ),
    .Q(_053_[2]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_1 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _214_ (
    .C(_045_),
    .CE(_056_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[17]_copy_2 ),
    .Q(_056_[2]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_2 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _215_ (
    .C(_043_),
    .CE(_048_[3]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[18]_copy_0 ),
    .Q(_014_[6]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_0 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _216_ (
    .C(_044_),
    .CE(_053_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[18]_copy_1 ),
    .Q(_053_[4]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_1 )
  );
  (* \always_ff  = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "../yosys_help_test/counter/mod_counter.sv:26.2-30.21|/home/jacobb00/yosys/yosys/share/xilinx/ff_map.v:68.41-68.95" *)
  FDRE #(
    .INIT(1'hx)
  ) _217_ (
    .C(_045_),
    .CE(_056_[5]),
    .D(\$auto$alumacc.cc:485:replace_alu$256.Y[18]_copy_2 ),
    .Q(_056_[4]),
    .R(\$abc$990$logic_or$../yosys_help_test/counter/mod_counter.sv:27$32_Y_copy_2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  LUT5 #(
    .INIT(32'd1381632)
  ) _218_ (
    .I0(_060_[2]),
    .I1(_057_[0]),
    .I2(_057_[1]),
    .I3(_056_[5]),
    .I4(_006_[1]),
    .O(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  LUT5 #(
    .INIT(32'd1381632)
  ) _219_ (
    .I0(_058_[2]),
    .I1(_051_[0]),
    .I2(_051_[1]),
    .I3(_048_[3]),
    .I4(_000_[1]),
    .O(_033_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:36.13-36.48" *)
  LUT5 #(
    .INIT(32'd1381632)
  ) _220_ (
    .I0(_059_[2]),
    .I1(_054_[0]),
    .I2(_054_[1]),
    .I3(_053_[5]),
    .I4(_002_[1]),
    .O(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015151515000000)
  ) _221_ (
    .I0(_058_[2]),
    .I1(_051_[0]),
    .I2(_051_[1]),
    .I3(_048_[3]),
    .I4(_064_[0]),
    .I5(_000_[6]),
    .O(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015151515000000)
  ) _222_ (
    .I0(_060_[2]),
    .I1(_057_[0]),
    .I2(_057_[1]),
    .I3(_056_[5]),
    .I4(_063_[0]),
    .I5(_006_[2]),
    .O(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015151515000000)
  ) _223_ (
    .I0(_058_[2]),
    .I1(_051_[0]),
    .I2(_051_[1]),
    .I3(_048_[3]),
    .I4(_067_[0]),
    .I5(_046_[2]),
    .O(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015151515000000)
  ) _224_ (
    .I0(_059_[2]),
    .I1(_054_[0]),
    .I2(_054_[1]),
    .I3(_053_[5]),
    .I4(_062_[0]),
    .I5(_002_[2]),
    .O(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015151515000000)
  ) _225_ (
    .I0(_059_[2]),
    .I1(_054_[0]),
    .I2(_054_[1]),
    .I3(_053_[5]),
    .I4(_065_[0]),
    .I5(_002_[6]),
    .O(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015151515000000)
  ) _226_ (
    .I0(_060_[2]),
    .I1(_057_[0]),
    .I2(_057_[1]),
    .I3(_056_[5]),
    .I4(_066_[0]),
    .I5(_006_[6]),
    .O(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015150015150000)
  ) _227_ (
    .I0(_058_[2]),
    .I1(_051_[0]),
    .I2(_051_[1]),
    .I3(_048_[3]),
    .I4(_000_[0]),
    .I5(_000_[1]),
    .O(_030_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015150015150000)
  ) _228_ (
    .I0(_060_[2]),
    .I1(_057_[0]),
    .I2(_057_[1]),
    .I3(_056_[5]),
    .I4(_006_[0]),
    .I5(_006_[1]),
    .O(_031_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015151515000000)
  ) _229_ (
    .I0(_060_[2]),
    .I1(_057_[0]),
    .I2(_057_[1]),
    .I3(_056_[5]),
    .I4(_012_[0]),
    .I5(_012_[5]),
    .O(_032_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015151515000000)
  ) _230_ (
    .I0(_059_[2]),
    .I1(_054_[0]),
    .I2(_054_[1]),
    .I3(_053_[5]),
    .I4(_010_[0]),
    .I5(_010_[5]),
    .O(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015151515000000)
  ) _231_ (
    .I0(_058_[2]),
    .I1(_051_[0]),
    .I2(_051_[1]),
    .I3(_048_[3]),
    .I4(_061_[0]),
    .I5(_000_[2]),
    .O(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015150015150000)
  ) _232_ (
    .I0(_059_[2]),
    .I1(_054_[0]),
    .I2(_054_[1]),
    .I3(_053_[5]),
    .I4(_002_[0]),
    .I5(_002_[1]),
    .O(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015151515000000)
  ) _233_ (
    .I0(_059_[2]),
    .I1(_054_[0]),
    .I2(_054_[1]),
    .I3(_053_[5]),
    .I4(_070_[0]),
    .I5(_052_[1]),
    .O(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015151515000000)
  ) _234_ (
    .I0(_060_[2]),
    .I1(_057_[0]),
    .I2(_057_[1]),
    .I3(_056_[5]),
    .I4(_071_[0]),
    .I5(_055_[1]),
    .O(_039_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015151515000000)
  ) _235_ (
    .I0(_058_[2]),
    .I1(_051_[0]),
    .I2(_051_[1]),
    .I3(_048_[3]),
    .I4(_014_[0]),
    .I5(_014_[2]),
    .O(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015151515000000)
  ) _236_ (
    .I0(_059_[2]),
    .I1(_054_[0]),
    .I2(_054_[1]),
    .I3(_053_[5]),
    .I4(_068_[0]),
    .I5(_010_[3]),
    .O(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/jacobb00/yosys/yosys/share/xilinx/lut_map.v:43.26-44.30" *)
  LUT6 #(
    .INIT(64'h0015151515000000)
  ) _237_ (
    .I0(_060_[2]),
    .I1(_057_[0]),
    .I2(_057_[1]),
    .I3(_056_[5]),
    .I4(_069_[0]),
    .I5(_012_[3]),
    .O(_042_)
  );
  (* keep = 32'd1 *)
  IBUF _238_ (
    .I(clk_copy_0),
    .O(_020_)
  );
  (* keep = 32'd1 *)
  IBUF _239_ (
    .I(clk_copy_1),
    .O(_021_)
  );
  (* keep = 32'd1 *)
  IBUF _240_ (
    .I(clk_copy_2),
    .O(_022_)
  );
  (* keep = 32'd1 *)
  OBUF _241_ (
    .I(_000_[1]),
    .O(count_copy_0[0])
  );
  (* keep = 32'd1 *)
  OBUF _242_ (
    .I(_000_[0]),
    .O(count_copy_0[1])
  );
  (* keep = 32'd1 *)
  OBUF _243_ (
    .I(_047_[1]),
    .O(count_copy_0[10])
  );
  (* keep = 32'd1 *)
  OBUF _244_ (
    .I(_047_[2]),
    .O(count_copy_0[11])
  );
  (* keep = 32'd1 *)
  OBUF _245_ (
    .I(_014_[2]),
    .O(count_copy_0[12])
  );
  (* keep = 32'd1 *)
  OBUF _246_ (
    .I(_014_[3]),
    .O(count_copy_0[13])
  );
  (* keep = 32'd1 *)
  OBUF _247_ (
    .I(_014_[4]),
    .O(count_copy_0[14])
  );
  (* keep = 32'd1 *)
  OBUF _248_ (
    .I(_049_[0]),
    .O(count_copy_0[15])
  );
  (* keep = 32'd1 *)
  OBUF _249_ (
    .I(_049_[1]),
    .O(count_copy_0[16])
  );
  (* keep = 32'd1 *)
  OBUF _250_ (
    .I(_014_[5]),
    .O(count_copy_0[17])
  );
  (* keep = 32'd1 *)
  OBUF _251_ (
    .I(_014_[6]),
    .O(count_copy_0[18])
  );
  (* keep = 32'd1 *)
  OBUF _252_ (
    .I(_000_[2]),
    .O(count_copy_0[2])
  );
  (* keep = 32'd1 *)
  OBUF _253_ (
    .I(_000_[3]),
    .O(count_copy_0[3])
  );
  (* keep = 32'd1 *)
  OBUF _254_ (
    .I(_000_[4]),
    .O(count_copy_0[4])
  );
  (* keep = 32'd1 *)
  OBUF _255_ (
    .I(_000_[5]),
    .O(count_copy_0[5])
  );
  (* keep = 32'd1 *)
  OBUF _256_ (
    .I(_000_[6]),
    .O(count_copy_0[6])
  );
  (* keep = 32'd1 *)
  OBUF _257_ (
    .I(_046_[2]),
    .O(count_copy_0[7])
  );
  (* keep = 32'd1 *)
  OBUF _258_ (
    .I(_047_[3]),
    .O(count_copy_0[8])
  );
  (* keep = 32'd1 *)
  OBUF _259_ (
    .I(_047_[0]),
    .O(count_copy_0[9])
  );
  (* keep = 32'd1 *)
  OBUF _260_ (
    .I(_002_[1]),
    .O(count_copy_1[0])
  );
  (* keep = 32'd1 *)
  OBUF _261_ (
    .I(_002_[0]),
    .O(count_copy_1[1])
  );
  (* keep = 32'd1 *)
  OBUF _262_ (
    .I(_010_[2]),
    .O(count_copy_1[10])
  );
  (* keep = 32'd1 *)
  OBUF _263_ (
    .I(_010_[1]),
    .O(count_copy_1[11])
  );
  (* keep = 32'd1 *)
  OBUF _264_ (
    .I(_010_[3]),
    .O(count_copy_1[12])
  );
  (* keep = 32'd1 *)
  OBUF _265_ (
    .I(_010_[4]),
    .O(count_copy_1[13])
  );
  (* keep = 32'd1 *)
  OBUF _266_ (
    .I(_052_[1]),
    .O(count_copy_1[14])
  );
  (* keep = 32'd1 *)
  OBUF _267_ (
    .I(_052_[5]),
    .O(count_copy_1[15])
  );
  (* keep = 32'd1 *)
  OBUF _268_ (
    .I(_053_[3]),
    .O(count_copy_1[16])
  );
  (* keep = 32'd1 *)
  OBUF _269_ (
    .I(_053_[2]),
    .O(count_copy_1[17])
  );
  (* keep = 32'd1 *)
  OBUF _270_ (
    .I(_053_[4]),
    .O(count_copy_1[18])
  );
  (* keep = 32'd1 *)
  OBUF _271_ (
    .I(_002_[2]),
    .O(count_copy_1[2])
  );
  (* keep = 32'd1 *)
  OBUF _272_ (
    .I(_002_[3]),
    .O(count_copy_1[3])
  );
  (* keep = 32'd1 *)
  OBUF _273_ (
    .I(_002_[4]),
    .O(count_copy_1[4])
  );
  (* keep = 32'd1 *)
  OBUF _274_ (
    .I(_002_[5]),
    .O(count_copy_1[5])
  );
  (* keep = 32'd1 *)
  OBUF _275_ (
    .I(_002_[6]),
    .O(count_copy_1[6])
  );
  (* keep = 32'd1 *)
  OBUF _276_ (
    .I(_002_[7]),
    .O(count_copy_1[7])
  );
  (* keep = 32'd1 *)
  OBUF _277_ (
    .I(_010_[5]),
    .O(count_copy_1[8])
  );
  (* keep = 32'd1 *)
  OBUF _278_ (
    .I(_010_[6]),
    .O(count_copy_1[9])
  );
  (* keep = 32'd1 *)
  OBUF _279_ (
    .I(_006_[1]),
    .O(count_copy_2[0])
  );
  (* keep = 32'd1 *)
  OBUF _280_ (
    .I(_006_[0]),
    .O(count_copy_2[1])
  );
  (* keep = 32'd1 *)
  OBUF _281_ (
    .I(_012_[2]),
    .O(count_copy_2[10])
  );
  (* keep = 32'd1 *)
  OBUF _282_ (
    .I(_012_[1]),
    .O(count_copy_2[11])
  );
  (* keep = 32'd1 *)
  OBUF _283_ (
    .I(_012_[3]),
    .O(count_copy_2[12])
  );
  (* keep = 32'd1 *)
  OBUF _284_ (
    .I(_012_[4]),
    .O(count_copy_2[13])
  );
  (* keep = 32'd1 *)
  OBUF _285_ (
    .I(_055_[1]),
    .O(count_copy_2[14])
  );
  (* keep = 32'd1 *)
  OBUF _286_ (
    .I(_055_[5]),
    .O(count_copy_2[15])
  );
  (* keep = 32'd1 *)
  OBUF _287_ (
    .I(_056_[3]),
    .O(count_copy_2[16])
  );
  (* keep = 32'd1 *)
  OBUF _288_ (
    .I(_056_[2]),
    .O(count_copy_2[17])
  );
  (* keep = 32'd1 *)
  OBUF _289_ (
    .I(_056_[4]),
    .O(count_copy_2[18])
  );
  (* keep = 32'd1 *)
  OBUF _290_ (
    .I(_006_[2]),
    .O(count_copy_2[2])
  );
  (* keep = 32'd1 *)
  OBUF _291_ (
    .I(_006_[3]),
    .O(count_copy_2[3])
  );
  (* keep = 32'd1 *)
  OBUF _292_ (
    .I(_006_[4]),
    .O(count_copy_2[4])
  );
  (* keep = 32'd1 *)
  OBUF _293_ (
    .I(_006_[5]),
    .O(count_copy_2[5])
  );
  (* keep = 32'd1 *)
  OBUF _294_ (
    .I(_006_[6]),
    .O(count_copy_2[6])
  );
  (* keep = 32'd1 *)
  OBUF _295_ (
    .I(_006_[7]),
    .O(count_copy_2[7])
  );
  (* keep = 32'd1 *)
  OBUF _296_ (
    .I(_012_[5]),
    .O(count_copy_2[8])
  );
  (* keep = 32'd1 *)
  OBUF _297_ (
    .I(_012_[6]),
    .O(count_copy_2[9])
  );
  (* keep = 32'd1 *)
  IBUF _298_ (
    .I(increment_copy_0),
    .O(_048_[3])
  );
  (* keep = 32'd1 *)
  IBUF _299_ (
    .I(increment_copy_1),
    .O(_053_[5])
  );
  (* keep = 32'd1 *)
  IBUF _300_ (
    .I(increment_copy_2),
    .O(_056_[5])
  );
  (* keep = 32'd1 *)
  IBUF _301_ (
    .I(reset_copy_0),
    .O(_058_[2])
  );
  (* keep = 32'd1 *)
  IBUF _302_ (
    .I(reset_copy_1),
    .O(_059_[2])
  );
  (* keep = 32'd1 *)
  IBUF _303_ (
    .I(reset_copy_2),
    .O(_060_[2])
  );
  (* keep = 32'd1 *)
  OBUF _304_ (
    .I(_017_),
    .O(rolling_over_copy_0)
  );
  (* keep = 32'd1 *)
  OBUF _305_ (
    .I(_018_),
    .O(rolling_over_copy_1)
  );
  (* keep = 32'd1 *)
  OBUF _306_ (
    .I(_019_),
    .O(rolling_over_copy_2)
  );
  assign _058_[1:0] = { _051_[0], _051_[1] };
  assign _067_[1] = _046_[2];
  assign _071_[1] = _055_[1];
  assign _062_[1] = _002_[2];
  assign _059_[1:0] = { _054_[0], _054_[1] };
  assign _060_[1:0] = { _057_[0], _057_[1] };
  assign _063_[1] = _006_[2];
  assign { _055_[3], _055_[0] } = _012_[4:3];
  assign { _050_[5], _050_[3:0] } = { _014_[5], _014_[3], _014_[1], _014_[4], _014_[2] };
  assign _068_[1] = _010_[3];
  assign _064_[1] = _000_[6];
  assign _069_[1] = _012_[3];
  assign { _046_[3], _046_[1:0] } = { _000_[5], _000_[6], _000_[4] };
  assign { _052_[3], _052_[0] } = _010_[4:3];
  assign _065_[1] = _002_[6];
  assign _066_[1] = _006_[6];
  assign _061_[1] = _000_[2];
  assign _048_[2:0] = { _014_[6], _000_[3:2] };
  assign _070_[1] = _052_[1];
endmodule
